### ISSUE TITLE
Auto-watch created repositories

### ISSUE THREAD

**Issue by kentcdodds** [github/hub#1014]
I have more than one issue reported without me knowing because I created the github repo using `git create` and apparently this doesn't "watch" the repo for me, so if I forget to do it myself, I don't get any notifications from the repo.

When I create the repository online, it automatically watches the repo for me. I would expect this to apply to repositories created with hub as well.

**Comment by mislav** [comment]
Thanks for reporting! I'll look into this.

**Comment by mislav** [comment]
@kentcdodds Is your automatic watching checkbox off on [/settings/notifications](https://github.com/settings/notifications)?

<img width="592" alt="screen shot 2015-10-31 at 2 15 07 am" src="https://cloud.githubusercontent.com/assets/887/10861091/3d40e3ea-7f75-11e5-96fb-d78b80966122.png">

**Comment by kentcdodds** [comment]
Ah! That's the problem. Thanks!

**Comment by pdf** [comment]
@mislav the issue is that hub behaviour differs from web UI behaviour.  When _creating_ a repository from the web, when that setting is disabled the creating user still automatically watches the repository.

It appears that setting aims to solve a different usage scenario - whether to watch a repo when a third-party grants push access to a repository, rather than the user's own repositories, so I don't think depending on that setting for hub to operate as expected is correct.
