### ISSUE TITLE
Add an option to rebase a fork from an upstream remote

### ISSUE THREAD

**Issue by opdavies** [github/hub#1047]
Maybe...
- Automatically add `upstream` when using the `hub clone` command on a forked repo.
- Automate the process of `git fetch upstream && git rebase origin/master` in a single command.

**Comment by mislav** [comment]
1. Good idea; was suggested before and will consider for next release.
2. Another good idea, but I'm wary of implementing that because it might not match everyone's workflow. How would you call such a command? Do we want to maintain that?

**Comment by mislav** [comment]
After some consideration, I have decided that—for now—this is best implemented in user scripts, rather than maintained in hub core. Now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3 https://github.com/github/hub/pull/2016

Thank you for suggesting!
