### ISSUE TITLE
Create release from command-line?

### ISSUE THREAD

**Issue by jamen** [github/hub#1049]
Would it be possible to create a release for a GitHub repository via the command-line through the API?

I think this would be useful for things like [`npm`](https://github.com/npm/npm) where we could create a bridge between the npm versions and github releases.

**Comment by mislav** [comment]
This is already available in beta:

```
$ hub release create -h
usage: git release create [-d] [-p] [-a <ASSETS_FILE>] [-m <MESSAGE>|-f <FILE>] <TAG>
```

Be aware, however, that this command is not polished yet and that its command-line usage might change in future versions. If you start using this in scripts, make sure that you revisit those scripts when you upgrade hub next.

Closing because this is on our roadmap already.

**Comment by mathikp** [comment]
any usage help/documentation for hub release command. What is [-d] [-p] ?

**Comment by mathikp** [comment]
Got it. -d for draft and -p for pre-release

**Comment by TheRealJoeLinux** [comment]
Is there a way to create the release in a different git remote? Such as upstream instead of origin?
