### ISSUE TITLE
Feature request: Offline pull request submission

### ISSUE THREAD

**Issue by JensRantil** [github/hub#1063]
I'm about to hop on a plane. Will work on a few features for a project. Would be nice to, in the spirit of a distributed VCS, add support for writing pull request texts offline and then submitting the pull request using a single `hub` execution. What do you think?

**Comment by mislav** [comment]
That's not a bad idea!

**Comment by notesoffline** [comment]
+1

**Comment by mislav** [comment]
After some consideration, I have decided that implementing this is best left as an exercise to the reader rather than being maintained in hub core.

For example:

1. Create files named `.queued-prs/<head-branch>` where the contents of the file represents PR title and body separated by a blank line;
2. When you get online, iterate through all `.queued-prs/*` in a loop and: `git push origin <head-branch> && hub pull-request -h <head-branch> -F .queued-prs/<head-branch>`

**Comment by JensRantil** [comment]
Makes sense!

**Comment by minipitbull** [comment]
hey excuse me who you are...
