### ISSUE TITLE
ci-status: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by greenrd** [github/hub#1100]
```
hub ci-status -v b116a403b9cbb95af90a809b65b36098d5c9c397
invalid character '<' looking for beginning of value
```

I am trying to use it against a GitHub Enterprise instance.

**Comment by mislav** [comment]
Thanks for reporting! You can get more detailed debugging info by adding an environment variable `HUB_VERBOSE=1 hub ci-status …`

This error message tells me that instead of a JSON response, HTML was returned instead for some reason, most likely a 4xx–5xx error page. Possibly the Enterprise instance has problems? Or it might be too old to support the Statuses API?

Anyway, if you use the debugging mode, you will get more info that you can share here (just remember to strip away sensitive info such as tokens). Upgrading hub to the latest master version can also provide you with a bit more descriptive error message.

**Comment by greenrd** [comment]
`HUB_VERBOSE=1` shows that this bug is occurring because the GHE instance is redirecting to our third-party SSO provider. Interestingly, this bug never occurs when I use `hub pull-request`.

**Comment by mislav** [comment]
@greenrd Thanks for checking that! Any idea why GHE is redirecting to the SSO? Maybe the token hub is using doesn't have sufficient privileges to fetch Status API?

**Comment by greenrd** [comment]
I tried to enable repo:status in my GHE settings, but it said some of the permissions are included in other persmissions and only the minimal set of permissions have been saved. So I think that because I have enabled repo permission, repo:status is also enabled.

**Comment by mislav** [comment]
Could you generate a new permissive Personal Access Token, paste it into `~/.config/hub` (replacing the old oauth token) and see if the issue goes away?

Thanks for looking into this :bow:

**Comment by greenrd** [comment]
I... don't seem to have a `~/.config/hub` file! Not sure where the personal access token is being stored...

**Comment by mislav** [comment]
If you can make `hub pull-request` against your GHE instance but don't have `~/.config/hub`, the only place that the configuration might be obtained from is from `GITHUB_TOKEN` environment variable.

**Comment by queeno** [comment]
I believe this was happening because the request URL produced by the `ci-status` and `release` is not hitting the GitHub Enterprise API endpoint:

```
> GET https://[GHE URL]/repos/[ORG]/[REPO]/commits/[SHA]/status
```
rather than:
```
> GET https://[GHE URL]/api/v3/repos/[ORG]/[REPO]/commits/[SHA]/status
```

The wrong request URL results in an LDAP authentication page being returned. Hub cannot parse it, hence it returns the following error:

```
invalid character '<' looking for beginning of value
```

I have created a pull request (PR #1139) to remediate this issue.

**Comment by jonico** [comment]
@mislav: any idea when this fix will be part of a release?

**Comment by mislav** [comment]
@jonico I'm trying to make this a part of hub 2.3, but there are other parts that I also want to bake into that releaase that are holding it back. I'm trying to make it soon!
