### ISSUE TITLE
hub pull-request should push the branch to remote 

### ISSUE THREAD

**Issue by dufferzafar** [github/hub#1115]
I create a commit on a new branch and run `hub pull-request` only to be alerted by git that the branch has not been pushed to the remote. I then have to run: `git push --set-upstream origin {branchname}` before I can create a pull.

I feel that this functionality should be the default in `hub`, so if a branch is not already pushed, just push it to origin.

**Comment by mislav** [comment]
Thanks for the suggestion! This feature request is already known as #165 and I'm sorry I've never got around to implementing it. At first I wasn't convinced that we should publish anything automatically, but since I've increasingly become convinced that auto-pushing should be the right thing to do. Please track the other issue for updates!

**Comment by davidstosik** [comment]
Which remote will hub push the branch to, when the repo has multiple remotes?
Origin might be the originally forked repository, to which I don't have write permissions, right?

**Comment by mislav** [comment]
@davidstosik Using the API, we can detect which of the remotes you have write access to.
