### ISSUE TITLE
hub clone/create abbreviated mode won't use updated username

### ISSUE THREAD

**Issue by rockorrupted** [github/hub#1166]
Say there are 2 github accounts (USER A and USER B) after switching user from USER A to USER B, command "hub clone repo X"  would always clone the repo X from the initial USER which is the one of account A, but not account B. (I already made sure that account B' USER_NAME were updated in git config name&email, ssh keypair and mac keychain).

Similar issue also happens to hub create: it always creates a new repo under the initial USER from account A not account B which is the actual one in use. Again, I have checked that the new USER_NAME of account B has been set anywhere else (git config, ssh keypair, mac keychain...).
I tried reboot, which didn't help.

When switching user, I have carefully followed the instructions including this one and have not met any issues outside of Hub. http://mherman.org/blog/2013/09/16/managing-multiple-github-accounts/

Is there still any mistake on my part? Thank you for your time and investigation : ]

**Comment by mislav** [comment]
Hi. Sorry that this was confusing for you, since we don't support workflows for having multiple GitHub accounts very well. The thing you missed is the `~/.config/hub` file. That's where hub keeps OAuth authentication info including the username which you authenticated with, and after you switched to USER B in your git config and by swapping SSH keys, hub still remains using USER A auth info.

The solution is to expand your switching script to also swap out `~/.config/hub` with another configuration file when it's updating `~/.gitconfig`. You could have two copies of `~/.config/hub`, each for different user, and swap them out by renaming them around. Unfortunately, that's all the advice that I can give you about this, and the implementation is left as an exercise to you. Good luck!
