### ISSUE TITLE
`hub fork` should set origin -> fork and upstream -> original

### ISSUE THREAD

**Issue by dholdren** [github/hub#1167]
Following the [GitHub guides for collaboration](https://help.github.com/articles/configuring-a-remote-for-a-fork/), `hub fork` should really set the following remotes:
origin -> my fork
upstream -> original

As-is (taken from https://hub.github.com):
```
# Example workflow for contributing to a project:
$ git clone github/hub
$ cd hub
# create a topic branch
$ git checkout -b feature
  ( making changes ... )
$ git commit -m "done with feature"

# It's time to fork the repo!
$ git fork
→ (forking repo on GitHub...)
→ git remote add YOUR_USER git://github.com/YOUR_USER/hub.git

# push the changes to your new remote
$ git push YOUR_USER feature
```

To match the guides mentioned above, and the style of many GitHub users:
```
# It's time to fork the repo!
$ git fork
→ (forking repo on GitHub...)
→ git remote rename origin upstream
→ git remote add origin git://github.com/YOUR_USER/hub.git

# push the changes to your new remote
$ git push origin feature
```

**Comment by JBYoshi** [comment]
See #798

**Comment by dholdren** [comment]
@JBYoshi thanks. guess I missed that when I was looking around.  too bad there's no traction on that though. Looks like it needed to be a configurable option and not the default in order to get accepted.

**Comment by mislav** [comment]
@dholdren I agree with your proposal and you see that we've discussed this at length in the past. The reason why I haven't solved this yet because I was reluctant to make a breaking change. But at some point, I will have to, I guess, or introduce an opt-in mechanism via configuration. In any case, I'm closing this as duplicate, and please follow the other related issues for updates.
