### ISSUE TITLE
'which git' - git: aliased to hub

### ISSUE THREAD

**Issue by welly** [github/hub#1168]
I've just installed hub and finding when I run which git, it always reports:

git: aliased to hub

Any suggestions why this might be occurring?

**Comment by mislav** [comment]
Yes. The installation instructions for hub suggest that you add this to your shell initialization file:

```sh
eval "$(hub alias -s)"
```

This adds the alias that `git` invokes `hub` each time. For normal git commands, `git ...` invocations will keep working for you as before. However, hub will add extra functionality to certain commands such as `git clone`, `git fetch`, etc. Please see `man hub` or `hub help hub` for more information on “expanded” git commands.

You can choose not to add the alias. Simply remove the `eval` line from your shell rc file. You will need to interact with hub explicitly by calling `hub ...` instead of `git ...`, but that's about it.
