### ISSUE TITLE
Password prompt for public repositories using user/repo and SSH protocol

### ISSUE THREAD

**Issue by michaelmior** [github/hub#1197]
I always get prompted for my GitHub username and password, even for public repositories. This information is not even used (I can enter in garbage and the clone still works). This only happens when I run `hub clone github/hub` and not `hub clone git@github.com:github/hub.git`. Also, this only happens when my global `.gitconfig` has `hub.protocol = ssh`.

**Comment by mislav** [comment]
Hi, sorry I never got back to you on this one.

Hub will try to ask you for username/password once, even for public repositories, because it wants to store an OAuth token and use it whenever it needs to access the API. This is separate of git cloning operation. Before, if you entered gibberish, the clone still proceeded, because it's not strictly necessary for that operation, but later releases fixed this confusion by actually aborting the process if the password is invalid.

Once you authenticate with hub, it saves the token and doesn't ask you again.

**Comment by michaelmior** [comment]
This seems to be resolved now with an update to `hub`, but just to clarify, `hub` was not saving the token and I was being asked for my password repeatedly.

**Comment by mislav** [comment]
@michaelmior I'm glad an upgrade solved this for you! If you still have a problem with token not being remembered in your `~/.config/hub` file, please reopen this. Thanks!
