### ISSUE TITLE
[Feature Request] Command to create comments on pull requests

### ISSUE THREAD

**Issue by nchen-lv** [github/hub#1203]
Not sure if this is possible, but it would be helpful to be able to add/create new comments to existing pull requests.  This would work hand in hand w/ [Jenkins pull request builder plugin](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin) which uses PR comments as trigger phrases for merge/build.

**Comment by stensson** [comment]
Just checking here, are there still no plans to add this feature?

I would love to have a command like 

  `hub comment <issue-no/PR-no> -m "comment content"`

for a few use cases. 

I primarily want this in order to add a reminder comment with a task list at the _bottom_ of a PR with a lot of commits. For example to remind the user to review the code and docs before merging a huge `release` branch with the past 4 weeks of commits into `master`. If this reminder is only in the PR description at the top, it is likely to be missed. 

Another use for it could be for an automated build/test system to add some details about the build into a comment.

If I remember the Github v3 API correctly, issues and PRs are the "same thing", which means this command could be used to comment issues and PRs alike.

**Comment by mislav** [comment]
There is a PR open to add a `hub comment` command #1465

I still haven't had time to properly review it and reach a decision about whether I like its API or do I imagine it to be different.

**Comment by sebszocinski** [comment]
+1 on this, I installed this planning to do just this and was bummed when I found out it's not a feature

**Comment by mislav** [comment]
After some consideration, I have decided that—for now—this is best implemented in user scripts, rather than maintained in hub core. Now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3 https://github.com/github/hub/pull/2016

For example, see the resolution in https://github.com/github/hub/issues/623#issuecomment-457859832

Thank you for suggesting!
