### ISSUE TITLE
brew install --HEAD hub; hub --version => 2.2.0.gc25e33e

### ISSUE THREAD

**Issue by nicolaiskogheim** [github/hub#1222]
The last released version of hub is 2.2.3, can be installed with a regular `brew install hub`. However, when installing from `--HEAD`, `hub --version` reports `2.2.0.gc25e33e`. I wasn't able to locate commit `gc25e33e` so I don't know what that corresponds to.

```
$ brew rm hub && brew install hub --HEAD
Uninstalling /usr/local/Cellar/hub/HEAD-c25e33e... (7 files, 11.4M)
==> Cloning https://github.com/github/hub.git
Updating /Users/nicolai/Library/Caches/Homebrew/hub--git
==> Checking out branch master
==> script/build -o hub
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/hub/HEAD-c25e33e: 7 files, 11.4M, built in 8 seconds

$ brew info hub
hub: stable 2.2.3 (bottled), HEAD
Add GitHub support to git on the command-line
https://hub.github.com/
/usr/local/Cellar/hub/HEAD-c25e33e (7 files, 11.4M) *
  Built from source on 2016-08-07 at 21:40:28
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/hub.rb
==> Dependencies
Build: go ✔
==> Options
--without-completions
	Disable bash/zsh completions
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions

$ hub --version
git version 2.9.2
hub version 2.2.0-gc25e33e
```

**Comment by mislav** [comment]
That's expected, but thanks for reporting. I can see how this can be confusing, making you think like you have an older version, but this is due to the fact that 2.2.x releases were tagged off `2.2-stable` branch, not master. Commits in master, therefore, are not aware of these tags having happened, and the closest tag to them is 2.2.0.

That's why there is the `-g<SHA>` appended to the version: so that the version identifier is more precise. The commit is c25e33e and you've indeed build from the latest state of master, which will become 2.3 eventually.

**Comment by nicolaiskogheim** [comment]
Thank you, that clears things up.
