### ISSUE TITLE
Setup tracking branch when checking out PR

### ISSUE THREAD

**Issue by blueyed** [github/hub#1238]
I've just tried `hub checkout https://github.com/pytest-dev/pytest-django/pull/380` with hub from master (2.3.0-pre3), but apart from what is mentioned in the man page, it does not seem to setup a tracking branch (according to `git rev-parse --verify @{u} --abbrev-ref`)?

Does this maybe only happen when the remote exists already?

The man page (hub-checkout) seems to refer to the old behavior also still?!

```
EXAMPLES
       $ hub checkout https://github.com/jingweno/gh/pull/73
       > git remote add -f --no-tags -t feature git://github:com/jingweno/gh.git
       > git checkout --track -B jingweno-feature jingweno/feature
```

**Comment by mislav** [comment]
There may be some documentation outdated after the change, but the new checkout implementation is this: it mainly fetches from `refs/pull/NUM/head` into a local branch, without any tracking setup, because we presume that you likely don't have access to push back to the PR. The only exception is when the PR is coming from the same repo. In that case, it checkouts the branch that represents the PR's head and sets up tracking.

What was your expectation? Is there something we could be doing better, but still avoid littering your git repo with new remotes?

**Comment by blueyed** [comment]
I suggest that in cases where the remote already exists, the branch could be setup as a tracking branch: my use case is checking out a colleague's PR (from their fork) and then I could create fixup commits right there.  And given that I have push access even push them.
But also without having push access, it's still useful information I'd say.

I am not sure that remotes should get added by default - that might become a config option though: for some repos or in general you might still want it.

As for shortcuts: do you think something like `hub checkout PR$NUM` makes sense?  (that's what I am using in my shell function currently: just the number; which `hub-checkout` a prefix would make sense)
