### ISSUE TITLE
Markdown Pull Request Templates aren't supported when using `hub pull-request`

### ISSUE THREAD

**Issue by iserko** [github/hub#1247]
If you have a Markdown version of the pull request template `PULL_REQUEST_TEMPLATE.md` then formatting is lost and you must re-add it manually.

Example of filling out a PR using `hub pull-request`:
```
#### Ticket
Ticket value

#### Description
Description value

#### Mentions
Mentions Value
```

Then what you get on the web after creating the Issue/PR:
```
Ticket value

Description Value

Mentions Value
```

Instead of what I would expect

> #### Ticket
> Ticket value
> 
> #### Description
> Description value
> 
> #### Mentions
> Mentions value
> 

Probably because it comments out the titles

```
% hub --version
git version 2.9.2
hub version 2.3.0-pre3
```

**Comment by mislav** [comment]
Yes, this is a known issue due to the fact that our text editor phase treats every line starting with `#` as a comment, much like authoring git commit messages does.

As a workaround, you could set `git config --global core.commentChar %`, or to another character which isn't `#` and which isn't a common character to start a line.

**Comment by iserko** [comment]
@mislav nice workaround! Thanks, this solved it for me.

**Comment by rpunkfu** [comment]
@mislav Would be nice to add it to wiki / docs :)

**Comment by jasonkarns** [comment]
Another workaround is to use `====` and `----` underlining the headers, since that is also valid markdown for headers.
