### ISSUE TITLE
ci-status seem broken – always returns 'no status'

### ISSUE THREAD

**Issue by vermiculus** [github/hub#1274]
No matter what I try it seems, I can't get `hub ci-status` to give me something other than 'no status' – not even for *this* repository:

```
$ git remote -v
origin	git://github.com/github/hub.git (fetch)
origin	git://github.com/github/hub.git (push)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
$ hub ci-status
no status
```

**Comment by mislav** [comment]
The latest commit to master in this repository has `[ci skip]` for Travis, meaning that "no status" is expected here since this commit has never been tested: 4777bd363058213605ebb292b35ef1a6edb3663c

However if you specify any other commit, it should work: `hub ci-status origin/2.2-stable`

Do you have the latest version of hub?

**Comment by vermiculus** [comment]
Ah, forgot about `[ci skip]` – my apologies 😄 

2.28 works as expected.
