### ISSUE TITLE
`git browse issues` sending me to public github.

### ISSUE THREAD

**Issue by impguard** [github/hub#1275]
Hey!

I've set the hub host in my github to be an internal corporate github environment. When I run `git browse`, I get appropriately sent to this internal environment.

However, browsing subpages breaks and sends me back to my public github. Have I set something incorrectly?

**Comment by mislav** [comment]
Hi, thanks for reaching out!

The `browse` command is a little bit awkward right now in it that to browse subpages, you have to use this form:

```
hub browse -- issues
```

The `--` argument takes the place of 1st argument which is otherwise the name of the repo to browse. Since we're browsing the current repo, we have to somehow negate the 1st argument.

I'm planning to make this command easier by allowing the subpage to be 1st argument instead.

**Comment by impguard** [comment]
I see!

Yea, that makes sense, signalling the end of your command line options. I'm less familiar with Go bash commands, so I'll take a look at how it's implemented. Thanks for the answer though!
