### ISSUE TITLE
How does hub get the git cached username and password?

### ISSUE THREAD

**Issue by ericbrandwein** [github/hub#1337]
Sorry to bother, but I want to do the exact same thing in a script of mine and I don't know how to. I'm using SSH, and I used the MacOSX keychain to store my credentials.

**Comment by mislav** [comment]
Hub uses your username & password to exchange it for an OAuth token using GitHub's "Authorizations" API. The process is made more complex because it needs to support two-factor authentication too. However, then it's done, it stores the OAuth token in `~/.config/hub`. It never stores the actual password.
