### ISSUE TITLE
Forking, Updating

### ISSUE THREAD

**Issue by svkamp** [github/hub#1368]
So... lets see if i got this right....

hub clone name/repo
cd repo
hub fork (creates a fork of name/repo to myname/repo

adds an origin for both...

so... how does one pull updates from the origin, and apply them to the fork then push them to myname/repo ??? 

its a bit confusing

**Comment by mislav** [comment]
Hub encourages [the "triangular" workflow with git](https://github.com/blog/2042-git-2-5-including-multiple-worktrees-and-triangular-workflows), where you fetch from one remote (hub calls it "origin" by default, but some people name it "upstream") and push it to another remote (typically your fork).

Therefore:

```sh
# fetch latest "master" branch from upstream:
$ git fetch origin master

# merge in latest upstream updates to your "feature" branch:
$ git merge origin/master

# push your "feature" branch to your fork:
$ hub fork
$ git push -u svkamp HEAD

# open a pull request with these changes:
$ hub pull-request
```

**Comment by waldyrious** [comment]
@mislav it looks like @svkamp was asking about the particular task of updating a fork with changes from upstream, rather than about the generic triangular workflow.

I'd say this would be equivalent to running `hub sync` with the additional step (which you alluded to in #1265) of pushing the updated branches to the fork's remote.

I suppose adding an extra option to `hub sync` to push the branches would address this use case.

**Comment by mislav** [comment]
@waldyrious If you'd like to propose enchancements to the `hub sync` command, please open a new issue, detailing how you think the feature could work. For instance: should it only push already published branched, or push even unpublished ones too?
