### ISSUE TITLE
gitlab support plz

### ISSUE THREAD

**Issue by xxmyjk** [github/hub#1383]
**why this genius tools can't use in gitlab**

I love it.

**Comment by mislav** [comment]
This tool is sort of a [semi-official GitHub CLI tool](https://github.com/github/hub/issues/475). It serves as a GitHub workflow enchancer as well as a demonstration of what can be achived using our API. As such, it's not in our interest to support other platforms (GitLab, Bitbucket, etc.).

Theoretically, someone could submit a PR tomorrow that introduces a swappable adapter for various platforms, and implements GitLab API as an alternative to GitHub API. Technically, that's feasible. However, practically that's very difficult to maintain over the long run, since every feature addition or change would have to be synced between multiple backends.

When Go gets stable support for runtime plugins, we can reconsider this. That way the community can maintain the support for 3rd party adapters without us having to.

**Comment by xxmyjk** [comment]
thanks a lot.  : ) 👍

**Comment by zaquestion** [comment]
@xxmyjk We've got a hub-like cli going here: https://github.com/zaquestion/lab

**Comment by udayrajMT** [comment]
Just putting this here as it was a bit hard to find at the time - 
https://github.com/jdalrymple/gitbeaker
