### ISSUE TITLE
`hub user` - see contributor stats

### ISSUE THREAD

**Issue by jasonLaster** [github/hub#1388]
It would be great if there were a command where you could quickly look up a contributor. 

This command would be analogous to pulling in information from git commits and the github profile

```
cd debugger.html
hub user wldcordeiro
```

```markdown
**Wellington Cordeiro**   (https://github.com/wldcordeiro)

**Location** Salt Lake City 
**Email** wellington@wellingtoncordeiro.com 
**Website** http://wellingtoncordeiro.com

**23 Commits**

First Commit: July 23rd, 2016

* Remove feature flagging on "completed" features. (#1765)  *(2 days ago)*
* Merge pull request #1727 from jasonLaster/fix-yarn  *(5 days ago)*
...
```

**Comment by mislav** [comment]
Interesting idea. However, I'm not conviced yet that this is something that belongs on the command line. Basically, what you're describing is a text representation of a user's profile such as we can see on the web? I'm just not sure whether this command would be used that much.

**Comment by mislav** [comment]
Oh I just realized—the "23 commits" in your above example are contributions scoped to the current repository? However, how would I find out about GitHub username `wldcordeiro` in the first place? The commit information in git doesn't include GitHub usernames; just full names + email.

**Comment by mislav** [comment]
After some consideration, I have decided that—for now—this is best implemented in user scripts, rather than maintained in hub core. Now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3 https://github.com/github/hub/pull/2016

Thank you for suggesting!
