### ISSUE TITLE
non-standard git extension

### ISSUE THREAD

**Issue by TrentonAdams** [github/hub#1393]
This git extension is developed in a non-standard way.  It is traditional to create commands called "git-name" where "git name" would be the command you run.  Then all you do is put "git-name" in the path.t

**Comment by mislav** [comment]
hub also extend some existing commands such as `clone` and `checkout`. This wouldn't be possible by creating `git-clone` and `git-checkout` executables, because they would never be run. This is why hub needs to "wrap" git.

The new commands, such as `hub pull-request` or `hub create` could very well be implemented as executables named like `git-pull-request` and put into PATH. This wasn't feasible when this project was written in Ruby, but is something I'm considering lately as a possibility. However, it isn't a large priority for this project, because we can't switch to that approach 100%.
