### ISSUE TITLE
Add new command "project"

### ISSUE THREAD

**Issue by i02sopop** [github/hub#1394]
Add a new command to manage github projects (create a new project, create/delete columns, create delete notes, assing notes to issues, ...)

**Comment by mislav** [comment]
Thanks for the suggestion! Hub isn't trying to replicate all features of GitHub.com. Mostly, we're trying to make some features available on the command-line if it makes sense, like creating a repo (because you need to push the local repo somewhere) and opening a pull-request (a natural next step after pushing a new branch). But some features don't make as much sense on the command-line, like Projects. I think Projects are best left for the web interface for now.

**Comment by sloanlance** [comment]
I disagree, @mislav.  Although some project features may not be appropriate for use from a CLI, others would be very helpful.

For example, I recently used the [ghi](/stephencelis/ghi) CLI to create many issues in a repo.  Now I'd like to add cards for the new issues to an existing project column in that repo.  ghi doesn't support that, so I hoped GH's hub would.  Without a programmatic way of adding issue cards to project columns, I'll need to drag dozens of cards one by one.  I'm not looking forward to that.

Please consider reopening this issue.  Would it help if this issue (or a replacement one) had a narrower focus, like specific functions of the project feature?

**Comment by mislav** [comment]
@sloanlance I agree that hub should be useful as a tool for automation from the command-line, e.g. creating new issues or PRs in bulk if there is a need for that. Your use-case for creating corresponding project cards makes sense. But, I'm not sure if I want to implement the full scope of handling projects.

I will reopen this to see if it garners interest.

**Comment by sloanlance** [comment]
Thank you, @mislav.  If I have free time, I'd be happy to contribute to the project.  (At least make an attempt, since I've never developed with Go.)

**Comment by mislav** [comment]
I've never developed with Go either, before one contributor rewrote this whole project from Ruby to Go 😆

**Comment by sloanlance** [comment]
Great!  I guess we're both Bantha poodoo, then.  😉

**Comment by stefanieberizka** [comment]
I support this feature as well. GitHub has already made the API's available. I think this would be useful for a lot of people.

https://developer.github.com/v3/projects/

**Comment by mislav** [comment]
After some consideration, I have decided that—for now—this is best implemented in user scripts, rather than maintained in hub core. Now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3 https://github.com/github/hub/pull/2016

Thank you for suggesting!

**Comment by diversemix** [comment]
I'm writing this in case any other dev comes by like me ... I stumbled on this page wanting to see if we had this feature - good to know about `hub api` thanks @msilav.

After searching - I found these scripts a good starting point for what I needed: https://github.com/mislav/hub-api-utils/tree/master/bin
