### ISSUE TITLE
remote: Repository not found in pull command 

### ISSUE THREAD

**Issue by veerpalkurmi** [github/hub#1402]
Hi ,

I am new in git so please can you help me figure out below exception and how  i can  resolve it.
i am running pull command:  **git pull origin develop**  and getting below exception 
**remote: Repository not found.
fatal: repository 'https://github.com:443/perfectcommerce/webprocure.git/' not found**

Thanks,
Veer

**Comment by mislav** [comment]
Hi, you seem to have a general problem with git, which I don't think is related to this project which is called "hub" and is a tool that wraps git, but is separate.

I'm going to assume that the repository that you're cloning is a private repository. As such, you will need to set up authentication so that your git can communicate with GitHub. Please [start from this help article](https://help.github.com/articles/https-cloning-errors/).

If you have more problems with GitHub, you can contact support@github.com. This issue tracker is for a project called "hub", and only applies if you downloaded and are using said project on the command-line.

Good luck!
