### ISSUE TITLE
Frequent `fatal error: MSpanList_Insert` on Sierra

### ISSUE THREAD

**Issue by lastobelus** [github/hub#1405]
OS X:
10.12.3 (16D32)

I'm using hub through the latest brew package:

    brew update; brew outdated

    > Already up-to-date.
    > Homebrew 1.1.9
    > Homebrew/homebrew-core (git revision c461; last commit 2017-02-11)

    hub --version

    > git version 2.11.1
    > hub version 1.10.2

    brew list --versions go

    > go 1.7.4_2 1.7.5

Error happens about once every 10 or so git commands. I think it might happen more frequently when running a command in a repo thats different than the last repo a command was run in.

Here's a sample stack trace:
```
failed MSpanList_Insert 0x747000 0x5fbf0a7a9368 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x67cb5b)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/panic.c:520 +0x69
runtime.MSpanList_Insert(0x696808, 0x747000)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/mheap.c:618 +0x8a
MHeap_FreeLocked(0x692800, 0x747000)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/mheap.c:447 +0x1a6
MHeap_Grow(0x692800, 0x10)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/mheap.c:341 +0x1ae
MHeap_AllocLocked(0x692800, 0x1, 0x2)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/mheap.c:222 +0x379
runtime.MHeap_Alloc(0x692800, 0x1, 0x10000000002)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/mheap.c:178 +0x7b
MCentral_Grow(0x69ac18)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/mcentral.c:265 +0x89
runtime.MCentral_CacheSpan(0x69ac18)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/mcentral.c:84 +0x14b
runtime.MCache_Refill(0x743000, 0x2)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/mcache.c:78 +0x119
runtime.mallocgc(0x10, 0x0, 0x10)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/malloc.goc:152 +0x30e
runtime.malloc(0x10)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/malloc.goc:264 +0x39
runtime.mallocinit()
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/malloc.goc:575 +0x2a5
runtime.schedinit()
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:150 +0x36
_rt0_go()
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/asm_amd64.s:91 +0x114
```

**Comment by lastobelus** [comment]
It seems like hub is using a very old version of go? but doesn't even list it as installed.

**Comment by lastobelus** [comment]
any tips on how I get a properly built hub from brew?

**Comment by lastobelus** [comment]
ls /usr/local/Cellar/go/1.3.3

    > ls: /usr/local/Cellar/go/1.3.3: No such file or directory

**Comment by lastobelus** [comment]
I did  a `brew unlink hub; brew install hub` and it seems to have gotten me a newer version of hub. Closing this for now, will reopen if the error crops up again.

**Comment by Zteve** [comment]
Upgrading to High Sierra caused this problem for me hard (setting up shell I executed `go get -v github.com/github/hub`, and the `hub alias -s` command fails with vomit).

After re-installing git and go _and_ hub (with `go get -u ...`) all to no avail, I eventually realised that I was installing all these (_except_ `hub`) with MacPorts.

(I have resisted homebrew since I need complete control over dependencies of dependencies, and don't necessarily want the most recent versions of everything — anyway it is hard to switch to brew from port.)

Anyhoo; instead of building hub myself (with go) I decided to see if macports had it — it does! So I removed the "setup" for hub, and installed hub with `port install hub` (which checks for dependency versions) and all is now well.  Just a note in case anyone else is still using Macports, like me.
