### ISSUE TITLE
Low-level API access

### ISSUE THREAD

**Issue by vermiculus** [github/hub#1416]
Should be linked #1232 and #1407

There've been a lot of feature requests over at magithub/hub#72 that would be best served by this idea of a API/authentication middleman.  Maybe something like

```sh
hub api get /repos/:owner/:repo/issues --owner=github --repo=hub
hub api patch /repos/:owner/:repo/issues/:number \
              --owner=github \
              --repo=hub \
              --number=1232
              --api-data='{"state":"closed"}'
```

and just return the response as the raw JSON for now.

**Comment by mislav** [comment]
That's a good idea, but I'm going to close this in favor of your other issue #1407, because they are about the same topic: providing a lower-level interface for script authors. Yes, I envision this interface to be both read and write.

In fact, several months ago I have started writing a `hub api` command that basically exposes GitHub's REST API (we call it API v3). Your proposal above is very close to what I was writing 😄  But, then GitHub announced GraphQL, which is still in beta, but I would like to start constructing this API functionality against that, since GraphQL is the future.

With GraphQL, we can fetch as much or as little data as we need using a **single** server request.
