### ISSUE TITLE
Create a room on gitter.im?

### ISSUE THREAD

**Issue by mareksuscak** [github/hub#1462]
I recently had some questions about the release schedule because I'm interested in the new GitHub templates integration which has recently been added and is only available in a prerelease. But I didn't know where to ask. 

Would it be a bad idea to create a room on gitter.im? What do you guys think?

**Comment by mislav** [comment]
We will consider adding a community chat room for support and other misc. questions. In the meantime, opening an issue like this is fine.

Regarding release schedule: there is none, but I'm working slowly towards the next stable release. The reason why it's taking so long is that I'm the only person at the moment working on this fairly large project. In the meantime, feel free to download the prereleases, since they're of good quality and have tons of new features.

**Comment by mareksuscak** [comment]
Thanks for the answer. Just figured that pre-releases can be installed via homebrew like so:

```sh
brew install --devel hub
```

**Comment by mislav** [comment]
@mareksuscak Nice! I didn't know that.
