### ISSUE TITLE
`hub checkout` asks for username and password

### ISSUE THREAD

**Issue by pitrou** [github/hub#1486]
This is annoying, as I normally use a SSH key for authentication.
```
$ hub checkout https://github.com/python/cpython/pull/1785
github.com username: pitrou
github.com password for pitrou (never stored): ^C
```

I've tried using a git URL instead but of course it doesn't work:
```
$ hub checkout git@github.com:python/cpython/pull/1785
error: pathspec 'git@github.com:python/cpython/pull/1785' did not match any file(s) known to git.
$ hub checkout git@github.com:python/cpython.git/pull/1785
error: pathspec 'git@github.com:python/cpython.git/pull/1785' did not match any file(s) known to git.
```

**Comment by mislav** [comment]
By attempting the checkout a pull request URL, you are using a hub-specific feature (as opposed to plain git), and hub features need to access the GitHub API. GitHub API can only be accessed over HTTPS, using either username/password or Personal Access (OAuth) token. This is **completely separate from what git does** when cloning/pushing/pulling, since git can use SSH keys, but GitHub API can't be accessed using SSH keys.

The summary of this story is, if you want to use hub features, you will have to authenticate (one time) with your username and password, and there is no possibility to use SSH keys, due to technical restrictions of the API.
