### ISSUE TITLE
refactoring: use google/go-github

### ISSUE THREAD

**Issue by charlierudolph** [github/hub#1487]
Just wanted to check in to see if you knew about this: https://github.com/google/go-github. I can't find any reference to it in the repo or in issues

**Comment by mislav** [comment]
I just found out about this project recently. It looks neat! However, we won't switch to it, because it would require a lot of code changes, and there wouldn't be much payoff. Instead, I envision future versions of hub to switch to consuming GitHub's GraphQL API instead of the RESTful "v3" API that we're using right now.

If go-github consumed the GraphQL API, I would consider switching to it.
