### ISSUE TITLE
Hub commands take precedence over user-created Git aliases

### ISSUE THREAD

**Issue by hkdobrev** [github/hub#1490]
I have a Git alias configured in `~/.gitconfig` like that:

```
[alias]
    sync = "!git pull --rebase && git push"
```

However, when I run `g sync` (where `g` is an alias to `hub`) it runs `hub-sync` instead of my own alias.

I think this is different than #153 as it is a different use case.

I think the user-generated aliases should always take precedence over hub commands. There is no easy way to circumvent this other than typing `\git sync` which is counter-intuitive as this is an alias to save typing.

I'm sorry if there was another issue discussing this problem.

**Comment by arichiardi** [comment]
Agree that aliases should win.

**Comment by mislav** [comment]
Core git has a rule that aliases should never win over an existing git command (either a core command or any kind of `git-*` executable in the PATH). Even though hub right now doesn't split its subcommands into `git-*` executables, we still pretend as if that was the case, and treat aliases accordingly.

I understand that this is inconvenient for you, but the reason why `git sync` alias doesn't work for you is because you've installed a utility that basically provides a `git-sync` executable, which takes precedence. The solutions are to either name your alias something else, or to avoid aliasing hub as git and remembering to ese `hub <command>` syntax whenever you need to access hub features.

**Comment by hkdobrev** [comment]
Thanks for the explanation.
