### ISSUE TITLE
hub fork doesn't add remote if fork exists

### ISSUE THREAD

**Issue by Laphatize** [github/hub#1493]

**Comment by DancingQuanta** [comment]
Works for me, what version is your `hub`? Mine's 
```
$ git --version
git version 2.12.3
hub version 2.3.0-pre9
```

**Comment by mislav** [comment]
@laphatize Could you prove more information please? We've had this feature for a long time now and it's covered by our test suite. If it's broken for you, please tell us your version of hub and steps to reproduce.

**Comment by MikeTLive** [comment]
when a repo of same name under a different org is forked,
the github UI names the second fork name-1
when the hub command attempts to fork that same repo,
Error creating fork: user/repo already exists on github.domain

github enterprise 2.8
$ hub --version
git version 2.14.1
hub version 2.2.9

**Comment by davidcurrie** [comment]
Just to reiterate (as I had to read the comment from @MikeTLive twice before I realized what he was saying was true in my case): if you `hub fork` in a clone of, say, `github.com/orgx/repoy`, and you already have a fork of a repo of the same name but from a different org e.g. `github.com/orgz/repoy` then you get the "already exists" message rather than it being added as a remote (which is probably not what you wanted).

As he then says, a friendlier thing for `hub` to do at this point would be to replicate the behavior of the GitHub UI and offer to create a fork with a different name.

**Comment by mislav** [comment]
> a friendlier thing for `hub` to do at this point would be to replicate the behavior of the GitHub UI and offer to create a fork with a different name.

That would indeed be friendlier! But, the GitHub API doesn't allow specifying a custom name when creating a fork. https://developer.github.com/v3/repos/forks/#create-a-fork

**Comment by davidcurrie** [comment]
:(

I guess all that leaves is a better error message explaining why nothing was done.

**Comment by mislav** [comment]
For now we're stuck with the current behavior.
