### ISSUE TITLE
Checking CI status of pull requests.

### ISSUE THREAD

**Issue by jasonkarns** [github/hub#1507]
This is mostly a question as I'm a bit lost in the rewrite of `issue` and the new `ci-status`...

(using hub version 2.2.9)

`hub issue` still prints pull requests for me

End goal is to check the CI status of a pull request. I can grab the issue number after checking `hub issue`.

I optimistically tried `hub ci-status 123` hoping for status of PR 123. (not really expecting that to work, though it would be nice)

The error message made me rather assume that the command is dereferencing branches to commits locally with git, and _then_ hitting github with the dereferenced sha.

I have git configured to fetch PRs as refs:

```
$ git remote show origin 
* remote origin
  Fetch URL: git@github.com:nodenv/node-build.git
  Push  URL: git@github.com:nodenv/node-build.git
  HEAD branch: master
  Remote branches:
    master                tracked
    refs/pull/1/head      tracked
    refs/pull/10/head     tracked
    refs/pull/101/head    tracked
    refs/pull/104/head    tracked
    refs/pull/105/head    tracked
    refs/pull/106/head    tracked
```

So I then tried `hub ci-status refs/pull/1/head` but that didn't work either. Is this feature supported somehow? I see that a general `pulls`-like command is on the roadmap. Any way to accomplish this until then?

**Comment by mislav** [comment]
Thanks for sharing your expectations with us and invocation styles that you tried, but didn't work.

Here is the current status of things:

* `hub issue` is significantly reworked in the prereleases (master branch), but not in 2.2.9. It has the ability to list PRs, but not their head branches, nor their CI status.
* A more specific `hub pr list` command is planned for the next prerelease. It will be able to list PR-specific information, such as base/head branches and CI status.
* `hub ci-status ARG` has a very simple implementation right now: ARG is interpreted as a **local** git ref and resolved as such. Therefore, PR number 123 won't work, nor will `refs/pull/1/head` because it's a _remote_ ref.

I'm open to your suggestions about how the APIs of `hub pr list` (still in the works) and `hub ci-status` can be more friendlier! But keep in mind that too much "friendliness" sometimes leads to more complex implementation and more to maintain in the longer run.

**Comment by jasonkarns** [comment]
Thanks for the info. I haven't thought about this much, other than my current desire to automate the checking (of CI) and merging of certain types of PRs.

**Comment by vishalseshagiri** [comment]
Is there a way to get commits in a PR using hub ? Thanks in advance...
