### ISSUE TITLE
Feature Request: manage organization and team membership

### ISSUE THREAD

**Issue by joshmorel** [github/hub#1508]
Hi hub team,

Have you considered adding ability to manage organization and team membership, as well as team creation using hub? I searched through open and closed issues and couldn't find any discussion on this so maybe it's just me who's interested.

I feel this would make hub more "complete" with regards GitHub workflows.

Thanks,
Josh

**Comment by mislav** [comment]
Hi, thanks for the suggestion! Unfortunately, I don't think organization and team management will ever be a part of hub, since hub mostly aims to help with workflows that make sense from the command line, such as git-related flows and collaboration features around issues, PRs, and releases. Organization management on GitHub.com has a complex UI that keeps evolving and would be hard to map to a text-only interface, especially with the introduction of nested teams.

I think managing organizations is best done through the web interface.
