### ISSUE TITLE
Possible way around "locked" branches - Merging in PR's to Master for example

### ISSUE THREAD

**Issue by luke-hill** [github/hub#1530]
I'm a bit wary of sharing this here, so firstly let me caveat with my environment settings.

Internal Github Enterprise v2.9.8 - Contributing to a PR which is inside a repo which is a part of a team. I am a member of the team but I have the approval rights.

It is possible I've found (Even though I have full admin access), to merge a PR into a "locked" branch without a review (Which I don't believe you should be able to do - even with full access).

Checking other branches, it appears that you do indeed need a review. However in certain circumstances you can get around this. This has allowed me in theory to merge in a branch into master without anyone looking / approving it.

Can someone from the GH community maybe advise?
**NB: I can reproduce this quite easily, just wary of sharing how**

**Comment by e-beach** [comment]
While this repository is owned by GitHub, I suggest approaching https://github.com/contact for disclosing this type of security flaw :ok_hand:. The GitHub organizaiton has hundreds of repositories; the purpose of each is to manage the code in that repo, not for miscellaneous issues in the GitHub platform.

**Comment by mislav** [comment]
Hi, thanks for reporting. This issue tracker is for a project called "hub" which is a command-line tool that wraps git. You didn't make it clear whether your problem is achieved using "hub", or your GitHub Enterprise web interface, or by other means. Nevertheless, this is not an appropriate place to discuss GHE issues, and instead please write to https://support.enterprise.github.com/hc/en-us/requests/new and feel free to disclose more details. Thank you!
