### ISSUE TITLE
[Feature] Query for PRs with a certain git sha and their status

### ISSUE THREAD

**Issue by DennisSchiefer** [github/hub#1541]
I'd like to see a command that allows to query a github repository for the existence of a PR  with a certain git SHA and the status of that request.

This would allow, among others, to implement a delete-merged-branches command that works on squashed merges.

Here is an implementation of something similar that I am looking for using the GitHub API: https://github.com/larsks/github-tools/blob/master/git-is-merged

**Comment by e-beach** [comment]
I'm trying to understand your request. Would it be correct to say that you want to check for whether a PR exists which contains a commit with the given SHA and whether that PR is open, merged, or closed?

**Comment by DennisSchiefer** [comment]
Correct. Similar to ci-status reporting the status of the CI jobs, it could report the status of the PR (open, merged, closed).

**Comment by mislav** [comment]
@DennisSchiefer Thanks for the suggestion. The planned interface to list pull requests (similar to `hub issue` command) is going to include a feature to filter the listing by certain criteria. The Status conditions and seaching by a commit SHA will be among those filters.

**Comment by mislav** [comment]
After some consideration, I have decided that—for now—this is best implemented in user scripts, rather than maintained in hub core. Now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3 https://github.com/github/hub/pull/2016

For example, finding a PR that introduces a certain SHA could potentially be done by using the Search functionality of the GitHub API.

Thank you for suggesting!
