### ISSUE TITLE
Can we please get an automated installation script

### ISSUE THREAD

**Issue by bbrala** [github/hub#1555]
I want to use this in our CI enviroment, but i'd like to have a simple way to install hub though a bash script. Unfortunately this doesn't seem possible at the moment, which is kinda sad.

Any chance this will be realised soonish? Dont really want to create my own.

**Comment by bbrala** [comment]
Small simple script for installation:

```
#!/bin/bash
echo "Getting download page for latest release"
downloadPage=$(wget https://github.com/github/hub/releases/latest -q -O -)
pause
echo "Finding download url"
downloadUrl=$(echo ${downloadPage} | grep -Po '(?<=href=")[^"]*(?=")' | grep hub-linux-amd64)
echo ${downloadUrl}
echo "Getting installation file"
wget "https://github.com${downloadUrl}" --output-document=github-hub.tar.gz
echo "Untarring..."
tar -zxvf github-hub.tar.gz
rm github-hub.tar.gz
cd hub-linux*
ls -la
echo "Installing"
sudo bash install
cd ..
rm -rf hub-linux*
```

**Comment by e-beach** [comment]
@bbrala I will work on hosting an expanded version of that script on a gist and make a PR to the README to use it as a general install script with `curl ...  | sudo sh`. Does that sound like what you have in mind?

**Comment by bbrala** [comment]
Yeah something like that would be helpful. It would make integration into a ci a lot easier. Which in turn make creating a PR from anautomated environment a lot easier :)

**Comment by mislav** [comment]
Your CI environment always runs on the same architecture, right? That means you can simply hardcode a URL to download, such as `hub-linux-amd64-2.3.0-pre10.tgz`, alleviating the need for an installation script.

```sh
wget -q https://github.com/github/hub/releases/download/v2.3.0-pre10/hub-linux-amd64-2.3.0-pre10.tgz -O- | tar -xzO \*/bin/hub > hub
chmod +x ./hub
./hub version
```

Benefits of this approach:

* You don't have to wait for us to publish an installation script
* You keep pinned to a specific version of hub, shielding you from future hub upgrades breaking your CI build
* No `sudo` required (simply use `hub` from within your project)
* Skip installing shell completion scripts and man pages because I'm guessing that you don't need those during your CI build

One other alternative is to vendor the linux build of hub right into your project so that it can run on CI without having to download anything from an external site, speeding up your builds by a few seconds.

**Comment by mislav** [comment]
Closing this in favor of earlier issue requesting this: #987. Work to create the script currently under way in https://github.com/github/hub/pull/1585
