### ISSUE TITLE
Allow creating PR on the original project from a branch on a fork

### ISSUE THREAD

**Issue by HaraldNordgren** [github/hub#1558]

**Comment by mislav** [comment]
Sorry, can you explain a little better? What are you trying to do? What have you tried so far? What hasn't worked?

**Comment by HaraldNordgren** [comment]
@mislav This is how I believe it works and doesn't work currently. Lets' say we have two repositories:

- `A`: Original project
- `B`: Fork of `A`

I work on a feature using `B`, create a feature branch and push to remote. The feature branch is solely a branch of the fork.

At this point I want to create a pull request for the original project, so I run my usual command

    hub pull-request

Now, instead of getting PR for `A`, I get the PR for `B`.

**Comment by JPry** [comment]
I use this workflow regularly, and it works correctly for me. However, there could be an issue with your repository settings. I believe that the branch that you *fork from* needs to be tracking to the original repository instead of the forked repository.

For example, let's say I have my remotes set with `origin` as the original repo, and `jpry` as my fork:
```
git remote -v 
jpry	https://github.com/JPry/hub.git (fetch)
jpry	https://github.com/JPry/hub.git (push)
origin	https://github.com/github/hub.git (fetch)
origin	https://github.com/github/hub.git (push)
```

The `master` branch is tracking to `origin`. I then made a new branch from master named `jpry_test`. This branch is pushed to the fork repo, and is tracked there. Here are my branches:

```
git branch -vv   
* jpry_test 5cf2e79 [jpry/jpry_test] Add test file
  master    e39364d [origin/master] Merge pull request #1563 from github/environment-variables-docs
```

If I run `hub pull-request`, then it correctly points to the original repo, because the original branch is tracked to the original repo. The following line is in the commented section of the Pull Request text:
```
Requesting a pull to github:master from JPry:jpry_test
```

I hope that helps you get things working correctly.

**Comment by mislav** [comment]
Thank you @JPry for your guidance.

@HaraldNordgren Hub also takes note of how your git remotes are named and makes assumptions about the "main" project based on that. For instance, it looks for remotes named "upstream", "github", and "origin" (in that order), and when it finds one it assumes that it points to the canonical version of the project (project A in your case) that PRs should be opened against.

How are your git remotes named?

**Comment by HaraldNordgren** [comment]
I never added an `upstream` remote because I didn't realize that I should. So, yes this works:

    git remote add $url
    hub pull-request

Although the PR title was not filled with the first paragraph from the commit message like I would have expected. Minor thing.

I'll close this. Thanks!

**Comment by mislav** [comment]
@HaraldNordgren Thanks for the update! If the PR title keeps being what you don't expect, you can open a new issue detailing what you're inputting in the text editor, what your expectation was, and what happened instead. Don't forget to include the hub version number!
