### ISSUE TITLE
Feature request: full or wildcard-based organization cloning

### ISSUE THREAD

**Issue by colindean** [github/hub#1617]
In many organizations to which I belong, including GHE organizations in the past, I've wanted to clone all of the repos in the org into a local directory or all that begin with a certain prefix.

I'd like to be able to do one or both of these:

1. `git clone myorg` - clones all of the projects in the organization _myorg_
2. `git clone myorg/prefix-*` - clones all of the projects in the organization matching the wildcard pattern `prefix-*`, so repositories named `prefix-main`, `prefix-lib1`, and `prefix-lib2` would all be cloned but `myorg/otherstuff` would not be.

I keep modifying [this script](https://gist.github.com/colindean/ffd30db8d868e71438db) for organizations but it'd be lovely if it was baked into hub, since hub is one of the first things I install or recommend during developer onboarding.

**Comment by mislav** [comment]
Thanks for the suggestion! It's not in our interest to support this feature, since some organizations can be very large, and most of users of hub will never need to clone every repository in an organization, since that use-case is rare. You will have to use the GitHub API manually to get the list of repositories, then you can clone each repository one by one by using git directly.
