### ISSUE TITLE
Add support for FIDO U2F keys

### ISSUE THREAD

**Issue by broady** [github/hub#1621]
This is kind of what I was getting at with #1150, but I didn't make my point well enough.

In its current state, `hub` only supports 2FA users using auth codes:
```
$ hub create
github.com username: broady
github.com password for broady (never stored):
two-factor authentication code: ^C
```

@mislav's workaround described in https://github.com/github/hub/issues/1150#issuecomment-251572332 works, but it's not pretty, and there's no UI flow for it.

**Comment by mislav** [comment]
I'm not sure how we could access a FIDO device from the command-line, and I'm going to make a call that we won't maintain this feature in hub. The 2FA code or a Personal Access Token work well as workarounds right now. The master branch now also has a feature where it accepts a Personal Access Token pasted instead of a password. 5f9b034b44264aa60a8e758fc92581a0311ad116
