### ISSUE TITLE
How can I change the git user once hub is installed and already has a github user configured?

### ISSUE THREAD

**Issue by hcristea** [github/hub#1648]
I have hub installed on windows and I would like to change the guthub user associated with the current hub installation. How can I do that?

**Comment by tobiasjstafford** [comment]
I just had the same question about a week ago, but didn't end up digging into the answer until you just reminded me about it with this question.

It turns out there's a `hub` file located under your `$HOME/.config` directory which contains the authentication info. Looks like you can also specify a different file with an environment variable of `$HUB_CONFIG`.

I don't know golang, so I didn't dig any further to see if there's a way to specify multiple users in that config file, or how you'd go about using them. Hope that helps!

**Comment by hcristea** [comment]
@tobiasjstafford, thanks a lot for taking the time to reply! 

Great info. I can take it from here :)

**Comment by ascarter** [comment]
Might be nice to add a `hub auth` command that could nuke the existing credentials and let you re-authenticate.

**Comment by mislav** [comment]
@ascarter This is planned in #225.

Thanks for helping @hcristea with a workaround! Sorry that this is not straightforward yet. Please follow the referenced issue for updates.

**Comment by hcristea** [comment]
The credit should go to @tobiasjstafford 👍 

The workaround is to delete the `hub` file from `$HOME/.config` and on next hub command like `clone`, or `pull-request` you get asked to auth again.
