### ISSUE TITLE
Expand <user/repo> when using git pull

### ISSUE THREAD

**Issue by ritiek** [github/hub#1651]
Just like `hub clone <user/repo>` expands to `git clone git://github.com/<user/repo>`, it would be nice to have a similar thing for `hub pull <user/repo>`.

**Comment by Tmplt** [comment]
Similar syntax would be nice for `hub checkout` when checking pull requests out. E.g. `hub checkout <user/repo>/pull/<pull-request>` instead of a URL, but this might be fit for another issue.

Or does this break compatibility with git?

**Comment by mislav** [comment]
Thank you for the feature idea! I gave it a thought since you've opened this but I don't think it's worth to invest into creating a wrapper for yet another git command. `hub pull OWNER/REPO` is not a syntax that I imagine being used very often, except for pulling from forks, in which case there is already the `hub fetch OWNER && git merge OWNER/BRANCH` combo available. Also, lately with hub we want to focus more on creating extra commands (such as `pull-request`, `release`, and `issue`) and less on extending existing git commands (such as `clone` and `checkout`) since those were historically harder to maintain.
