### ISSUE TITLE
Tab-completion for PowerShell?

### ISSUE THREAD

**Issue by tlycken** [github/hub#1661]
Is tab completion for powershell available from somewhere?

I can't find anything about it in the wiki, and searching for "hub tab-completion powershell" unfortunately gives me a lot of noise about tab-completion for random other things, that happens to be hosted on github...

**Comment by mislav** [comment]
From [the Readme](https://github.com/github/hub#shell-tab-completion): 

> hub repository contains tab-completion scripts for bash, zsh and fish.

So, no completion for PowerShell right now. We would consider accepting it in form of a PR, but I wouldn't know how to test it nor maintain it going forward. Because this doesn't fit on our roadmap right now, I'm closing this as #wontfix.

**Comment by tlycken** [comment]
I understand that this is probably out-of-scope for this repo, but I was hoping you might know about other projects that have already implemented it. But I take that as a no?

**Comment by mislav** [comment]
Yes, I don't know of any projects. I have very little familiarity with PowerShell.

**Comment by NotWoods** [comment]
If you're still looking for a solution, you can [use bash completions in PowerShell](https://www.paraesthesia.com/archive/2018/06/19/psbashcompletions-bash-argument-completion-in-powershell/) if you have Windows Subsystem for Linux or Git Bash.
