### ISSUE TITLE
hub ignore

### ISSUE THREAD

**Issue by mohsen1** [github/hub#1674]
Add a command for initializing a `.gitignore` file. Using data in https://github.com/github/gitignore it should accept options for type of project. 

Something like 
```sh
hub ignore nodejs
```

**Comment by mislav** [comment]
It's an interesting feature idea. Not sure if it fits on our roadmap, but I'll keep it open until we figure that out.

**Comment by giuscri** [comment]
What should happen when there's already a .gitignore?
1. Refuse to continue
```
$ hub init-ignore nodejs
`.gitignore` already exits in this git repository. Remove it before
running `hub init-ignore nodejs` # <- shameless copy of `vagrant init` error
```
2. No problem as the command just prints Node.gitignore content on stdout
```
$ hub ignore nodejs >> .gitignore
```

**Comment by sfdye** [comment]
Maybe this will be useful?
https://developer.github.com/v3/gitignore/

**Comment by mislav** [comment]
After some consideration, I have decided that—for now—this is best implemented in user scripts, rather than maintained in hub core. Now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3 https://github.com/github/hub/pull/2016

For example:
```sh
hub api gitignore/templates/Ruby | jq -r .source
```

Thank you for suggesting!
