### ISSUE TITLE
hub browse opens fork url instead of main repo

### ISSUE THREAD

**Issue by friederbluemle** [github/hub#1706]
**Scenario:**
I'm on a custom branch (pushed to my fork) in a repo with two remotes: `origin` pointing to the authoritative repo, and `fork`, pointing to my fork.
**Actual behavior:**
When entering `hub browse` it opens _the forked repo page_ in the browser.
**Expected:**
In 99 out of 100 cases I am **not** interested in my fork, but expect to see the main repo.
I understand this may be the current "expected" default behavior, however it would be much more logical to do something along the lines:

`hub browse` -> Open main repo
`hub browse -f` or `hub browse --fork` -> Open forked repo

Since _all_ my remote names for the respective authoritative repository are called `origin`, it would also be okay to have something like `hub browse origin` as a **predictable and guaranteed way** to open the "main" repo GitHub page in the browser.

Related: #1671

**Comment by kfkonrad** [comment]
I second this, can this please be taken into consideration?

**Comment by mislav** [comment]
Hi thank you for writing in.

Usually `hub browse` will open the repository indicated by the `origin` remote; it would only use `fork` if you are currently on the branch that is pushed to `fork`. This was the designed behavior for a long while now: https://github.com/github/hub/blob/08004b921836a3fa8ae6054ab273cdbf6da39f8c/features/browse.feature#L73-L79

I understand that this is inconvenient if you wanted to open `origin` instead, ignoring the current branch or where it's pushed. Right now, there is no way of achieving this with `browse`, and extending its functionality is not planned. `browse` suffers from a number of design flaws and instead of "fixing" it (and breaking backwards compatibility for whoever is using it right now), it's on our roadmap to replace it with a new command called `hub open` that will make it easier to navigate to branches, commits, and other objects will less magic behavior and in a more predictable manner.

But for now, I'm going to close this out for the sake of cleaning out the bug backlog, since I'm not sure what actionable item I can draw from this that would also keep backwards compatibility for current users of `browse`. If anyone has ideas, I welcome PRs!

**Comment by friederbluemle** [comment]
Thanks for the explanation @mislav Looking forward to a more flexible and useful new command!
