### ISSUE TITLE
`hub pr` conflicts with git alias `pr = pull-request`

### ISSUE THREAD

**Issue by xentek** [github/hub#1765]
Just updated hub to the latest version `2.3.0`, from I believe `2.2.9` (recently ran `brew cleanup` and `2.2.9` is the only other version I have on my machine at the moment).

I see that a `hub pr` command was added. Unfortunately, I had already added an alias to my `~/.gitconfig` that set `pr = pull-request`, and since it's not possible to override internal git commands with an alias, I will now have to go back to using the full `pull-request` or come up with another alias (`git cpr` just doesn't have the same intuitiveness) or resort to a shell alias (`gitpr`).

The damage is already done, and I don't expect this to be changed on my account, but it seems odd to have two commands for working with pull requests, instead of just adding the new `pr` subcommands to the existing `pull-request` command, which is how git commands are typically organized -- even those that have a default operation without a subcommand, but other behavior when a subcommand is provided , e.g. `git branch`, `git remote`, et al.

Hub is amazing and I make it a standard part of the toolkit for all of my teams, but this change was definitely a violation of [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), at least for me.

Cheers

**Comment by mislav** [comment]
Thanks for letting us know!

Unfortunately, the only way to never violate anybody's aliases is to **never ever** add new commands to hub. This will not happen because hub wants to grow. And now that `hub pr` is here, I can't remove it just to make your alias work again—the command is here to stay and will gain more features and subcommands over time.

You have two options:
1. Don't alias `hub` as `git` (this is what I do). This way, you can use `git` for regular git stuff, and `hub` for hub-only functionality. That way you can keep your `git pr` alias.
2. Implement a shell function to handle your aliasing needs, such as one suggested in https://github.com/github/hub/issues/1536#issuecomment-392895328.

Closing because I'm not sure what actionable item there is from your report. I can't delete `hub pr`, and I can't make `git pr` alias work while `hub pr` exists and `hub` is aliased to `git`.

**Comment by xentek** [comment]
@mislav There were no actionable items, so closing is expected. 

If `pr` is to replace `pull-request` in the near future (including getting the ability to create PRs) than I have something to look forward to. I will use the shell function shared in the other issue thread (thanks for linking to that) as a work around until such time that `pull-request` is replaced by or deprecated in favor of `pr`.

Cheers

**Comment by jvinding** [comment]
`pull-request` works fine, if I want it shorter I can add my own alias.

**Comment by jfelchner** [comment]
The better solution for this would have been to not have created a `hub` command which was this short.  People are significantly less likely to have an alias of `pull-request`.  They are significantly more likely to have an alias of `pr`.  There was no reason to make the `hub` command this short when, should people choose, they could have created `pr` as an alias.

**Comment by particledecay** [comment]
The `pr` subcommand looks like sloppy planning, IMO. There are two commands for working with pull requests, and the word `pr` doesn't line up with the already existing convention of fully spelled-out git subcommands (with the exception of `rm` and `mv`). In fact, it's the only hub subcommand that's abbreviated... and the full name already exists in a *different* subcommand that works on the exact same GitHub resources.

The implementation of `pull-request` and `pr` should have been done the way `release` is done, and like I said this just looks like it was done by two different people and they didn't talk to each other. Check out the help:

```
   pr             List or checkout GitHub pull requests
   pull-request   Open a pull request on GitHub
   release        List or create GitHub releases
```

I feel like the following would have been more consistent, discoverable, and user-friendly:

```
   pull-request   List or create GitHub pull requests
   release        List or create GitHub releases
```

**Comment by mislav** [comment]
@particledecay You're right, it wasn't well-thought through.

I made a call to call the `pr` command the way I did because `pull-request` already existed in a form that doesn't accept subcommands, and I wanted a PR command that has a number of subcommands. I also wanted people to have less to type. There were tradeoffs with each potential approach, and this issue describes one such tradeoff.

**Comment by particledecay** [comment]
@mislav would it be too much to ask to plan the next major version (3.x, breaking change) to behave this way?

It wouldn't affect anyone sticking to the 2.x version.

**Comment by mislav** [comment]
@particledecay In which way, exactly?

**Comment by particledecay** [comment]
@mislav consolidating both subcommands into a single `pull-request` command
