### ISSUE TITLE
Allow inviting collaborators

### ISSUE THREAD

**Issue by Jarred-Sumner** [github/hub#1783]
Something like this would be nice:

```bash
hub invite luke@lukemile.es
```

```bash
hub invite @lukemiles
```

Alternatively:

```bash
hub collaborators new luke@lukemile.es
hub collaborators new @lukemiles --admin
```

```bash
hub collaborators rm luke@lukemile.es
hub collaborators rm @lukemiles
```

```bash
hub collaborators
hub collaborators ls
```

**Comment by kelsier27** [comment]
I would like to work on this feature. Can you tell me more about how this should be implemented?

**Comment by mislav** [comment]
You would have to implement API calls for https://developer.github.com/v3/repos/collaborators/

You can take a look at `commands/release.go` as examples of how we query the API and do things with the result.

However, depending on the complexity of this implementation, we could choose not to accept it in hub. I've added the "feature" label to think about this, but it's not high on our roadmap.

**Comment by mislav** [comment]
After some consideration, I have decided that—for now—this is best implemented in user scripts, rather than maintained in hub core. Now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3 https://github.com/github/hub/pull/2016

Thank you for suggesting!
