### ISSUE TITLE
It appears that `hub release delete` fetches all releases as part of its operation and might make too many other API calls

### ISSUE THREAD

**Issue by Taytay** [github/hub#1793]
In an effort to delete our draft releases, I wrote this little one-liner:

`hub release -f "'%T' (%S) %n" --include-drafts | grep " (draft)" | awk '{print $1}' | xargs -t -n1 hub release delete`
(Further explained here: https://stackoverflow.com/a/51049361/544130 )

So far, so good, but since we have 100+ draft releases, I will call `hub release delete` 100+ times. That doesn't seem like it would be a problem on its face, but given how long `hub release delete` takes to operate, I'm beginning to think that it is fetching _all_ releases in the process of deleting a single release? Furthermore, I am now locked out with an `API rate limit exceeded`, further cementing the idea that `hub` might be making a lot more calls on my behalf than I would expect for a single delete call?

**Comment by mislav** [comment]
Thank you for reporting. When deleting a release, hub indeed fetches all releases in batches of a 100 records until it finds one with a matching tag name, then makes a `DELETE` request. For a repository of 500 releases, for example, this could potentially result in 6 HTTP operations.

I can't remember why we're not simply using the https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name endpoint to find a release by tag name, but I think that draft releases cannot be found using this endpoint since they're not published, and that the only way to find out the release ID of a draft release by its tag name is to iterate over all releases.

**Comment by Taytay** [comment]
Ah, I see @mislav. That makes sense. Now that I know that, when I consider how many releases we have, it makes sense that I ran out of my allotted calls. :)

The only way to make it slightly better would be to allow for me to delete multiple releases with the same command by passing in multiple releases in the same command line. But this is surely an edge case. You are free to close this. Thanks for the quick reply.

**Comment by mislav** [comment]
Make sure you're using at least hub v2.3.0 or newer! The operation to show or delete a specific release was significantly optimized in https://github.com/github/hub/commit/977cade509e9abc236376cbf0fb1e8753a2fd292.
