### ISSUE TITLE
checkout pr-url no longer adds remote or sets upstream

### ISSUE THREAD

**Issue by davidism** [github/hub#1795]
As a maintainer, I want to easily checkout PRs and push to those forks.

Previously, `hub checkout https://github.com/path/to/pr` would add a remote for the user's fork, fetch the PR branch, and set the branch upstream so that `git push` would push back to the PR.

However, now checkout only fetches the branch, it doesn't add a remote or set upstream. So I can fix up a PR, but I have no way to push back to the branch.

git version 2.18.0
hub version 2.4.0

**Comment by mislav** [comment]
Have you tried `git push`? https://github.com/github/hub/pull/1764

We _do_ set upstream configuration, which enables `git pull` and `git push` even without a separate remote. https://github.com/github/hub/blob/64e5fe6cbf49407daf9310bd9c0cd58bb1751161/commands/checkout.go#L131-L132

**Comment by davidism** [comment]
You're right, it does work. I think what was confusing me is that I use a prompt that shows the number of commits to be pushed, and it doesn't work when there's no remote. It seems like `git status` also won't show this information, which makes it hard to know what state the branch is in compared to the PR.

Not adding remotes does have the benefit of not cluttering the list with a bunch of one-off entries, but is that a good tradeoff?

**Comment by mislav** [comment]
> It seems like `git status` also won't show this information

You're right, that's a feature we lost when moving from generating a remote to no remote.

> Not adding remotes does have the benefit of not cluttering the list with a bunch of one-off entries, but is that a good tradeoff?

After a few years of hub adding remotes, yes I think that's a good trade-off. Otherwise we're left with no good mechanism of cleaning up those remotes after the PRs have been closed.

> IntelliJ / PyCharm doesn't understand where to push.

I can't help with 3rd-party tooling. I've made it so git understands where to push/pull from. If another git tool doesn't know how to parse this configuration, then I guess the git integration in that tool/IDE needs improving.

Closing since it's still easy to checkout PRs and then immediately push to those forks via simple `git push`, which addresses the original question.
