### ISSUE TITLE
pull-request should copy the pull URL to clipboard

### ISSUE THREAD

**Issue by rsanheim** [github/hub#182]
The pull-request command should copy the URL of the newly created pull-request to the clipboard (for os'es that can do that easily, i.e. `pbcopy` or whatever), as the typical workflow is to create the PR and then go to it in your browser.

**Comment by jasonkarns** [comment]
I'm :-1: on this. I thinks it's terribly impolite for tools to modify clipboard (and other environment things) without being instructed to do so.

I would be :+1: for a CLI option and/or could be set via config.

Doubly so, since hub already has the `-o` option which is even more streamlined for the "create pr, open in browser" flow.

**Comment by mislav** [comment]
> I would be :+1: for a CLI option and/or could be set via config.

Yes, I think that's an option that respects everyone.
