### ISSUE TITLE
Support repos with multiple templates

### ISSUE THREAD

**Issue by omgjlk** [github/hub#1822]
I have a repo with multiple templates, as [documented here](https://help.github.com/articles/about-issue-and-pull-request-templates/#issue-templates). However hub is trying to read the path of `.github/ISSUE_TEMPLATE` as a file rather than as a directory, by reading through [template.go](https://github.com/github/hub/blob/master/github/template.go). The client throws this error:

```
hub issue create
read /Users/omgjlk/src/gc2/.github/ISSUE_TEMPLATE: is a directory
```

I believe that the `template.go` code should check if the paths for `IssueTemplate` and `PullRequestTemplate` are directories, and if they are then provide a choice of which template to use.

**Comment by mislav** [comment]
Thank you for reporting! It's unfortunate that this throws an error rather than just continuing and ignoring the template directory altogether. As for support for multiple templates, I'm not sure if a prompt to select one is the right way to do. I'd rather people have select a template by explicitly passing `HUB_TEMPLATE=foo hub issue create` or `hub issue create --template=foo`.

PRs welcome!

**Comment by omgjlk** [comment]
Yeah those options would be fine too. In the short term I've worked around this with: `hub issue create -e -m "Title of issue"`, as that bypasses a template look up and just gives me an editor w/ the first line filed in.

I'm not really familiar with Golang, so a PR from me may take a bit, but I'll add to the queue as a thing to practice with 😁

**Comment by cycomachead** [comment]
Ran into this too. On 2.3 I had an error with `pull-request --push -r ...`, but on 2.5 I got an editor with no template. Not ideal, but better than an error. :)

My repo has a tree which looks like this:
```
- .github/
   | - PULL_REQUEST_TEMPLATE/
   |   | - schoo_upgrade.md
   | - PULL_REQUEST_TEMPLATE.md
```
