### ISSUE TITLE
hub init -g does not actually create the project

### ISSUE THREAD

**Issue by nhooyr** [github/hub#1831]
The docs state regarding the `-g` option to `hub init`:

```
       -g     After  initializing the repository locally, create a "USER/REPO"
              repository on GitHub and add it as the "origin" remote.
```

However see https://github.com/github/hub/blob/c60ca203c9ecfdb8e0693a0fc0edfa9d58dd00d1/commands/init.go#L72-L88

It only adds the url of the remote as if the project were to exist.

**Comment by mislav** [comment]
Our documentation was stale. We fixed it, but it hasn't yet been released: #1810

**Comment by nhooyr** [comment]
I think it's super useful to just be able to create a repository instantly and have the remote initialized and have it created on github. Do you think we could see a flag somewhere to do this in one step?

**Comment by nyl2002** [comment]
Please let me know if there is any page with example workflows explaining how this chaining works.
I get all kinds of unexpected errors such as "must be called in a 
repository" or needing to call "git push --set-upstream origin master" 
which then actually doesn't work smoothly.
Example: a public key vs. user password. When is which one used? It seemed to be different depending on if I created a repository on GitHub or with "hub create -p". And also depending on if it was created with or without original readme on GitHub. Hard to know what made the difference.

The git=hub aliasing you propose backfires I think because it makes it complicated and confusing to google for workflows.

**Comment by nyl2002** [comment]
It would be great to have an end-to-end list of required commands.
Starting from nothing till having a new directory, which is a git repository linked to a GitHub repository including being able to call git push without any further difficulties or requirements.

**Comment by mislav** [comment]
To create a new repository on GitHub from the command-line:

```sh
cd my-project
git init
git add . && git commit -m "It begins."
hub create -d "My new project"
git push -u origin master
# after this you can use simple `git pull/push`
```

To push to a repository that was initialized on GitHub with a README, you first have to clone it:

```sh
hub clone my-project
cd my-project
# ... make some changes ...
git push
```

Notes:

1. The reason why `git init`, `hub create`, and `git push` steps are separate is because different people's project creation needs are different and a single workflow wouldn't cover everyone's use case. Since people generally don't create multiple new GitHub projects per day, I'm hoping that executing a few short commands manually isn't too large of a task for a regular user.

2. You don't need to alias `hub` as `git`. In fact, I don't do it on my machine.

3. > Example: a public key vs. user password. When is which one used?

   Git will want to use ssh keys for clone/pull/push operations for repositories cloned over the `ssh://` protocol (sometimes also recognizable by urls starting with `git@`), which is the default protocol for hub operations unless you opt into HTTPS mode: `git config --global hub.protocol https`.

   Hub commands will **always ask you for username/password** on first run because they need to authenticate to the GitHub API, which is completely separate authentication from git clone/pull/push operations. See https://github.com/github/hub/issues/1644#issuecomment-359002547

4. > which then actually doesn't work smoothly.

   It sounds like you are expecting hub to work smoothly for your workflow, but you haven't really described your workflow. If there is a bug in hub, please tell us about the bug and about your `hub version`. If hub did something that you didn't expect, or if you have ideas how to have it work better, then please suggest some! But it would be helpful to talk in more detail and with more precision. For instance, if I run `hub <command> <args>`, what _exactly_ should happen?

Thanks for writing in! Sorry that this is still a bit of a mess. Hub is hard because git is hard.
