### ISSUE TITLE
hub remote add gives wrong url for Github repositories

### ISSUE THREAD

**Issue by marcosfelt** [github/hub#1832]
The default urls generated by hub for push do not work.

When I add a new Github repository as a remote using `hub remote add _USER_`, a git protocol url is created. For example, the output of `hub remote -v`on my repo is:

```
scici   git://github.com/scici/sci.git (fetch)
scici   git://github.com/scici/sci.git (push)
```
From what I understand, `git:://` url will not work on push because the git protocol [lacks authentication](https://git-scm.com/book/en/v1/Git-on-the-Server-The-Protocols#The-Git-Protocol).  The url should be https. 

I'd be willing to fix this if someone could point me in the right direction.

**Comment by mislav** [comment]
1. Which `hub version` are you using?
2. Do you have write access to `scici/sci` repo?
3. See “HTTPS instead of git protocol” at https://hub.github.com/hub.1.html

**Comment by marcosfelt** [comment]
@mislav thanks for the quick response.

1. I'm using ver 2.5.0
2. I do have write access.  I was able to push after manually changing the remote url to https.  Btw, this is the error I received:
```
 git push -u scici master
fatal: remote error:
  You can't push to git://github.com/scici/sci.git
  Use https://github.com/scici/sci.git
```
3. Thanks for pointing to that part of the documentation.  For the future, shouldn't push urls be https by default (because the git protocol isn't supported on push by github)?

**Comment by mislav** [comment]
Thank your for the details. I've figured out what's going on:

In other commands that generate a remote URL, we query the repo using GitHub API to determine whether you have push access to it, then we use the `git@github.com` URL format (SSH protocol) instead of the `git://` protocol. But, **we don't do it** in `hub remote add`, since that is pretty old code. Therefore, you will need to do `hub remote add -p _USER_` (notice the `-p` flag).

However, you can also configure hub to just use HTTPS for everything, which solves this problem and doesn't require you to optionally pass in `-p`. It all depends whether you want to use HTTPS or SSH for pushing to repositories.

**Comment by marcosfelt** [comment]
Thanks!
