### ISSUE TITLE
add methods to config to return api base url and upload url

### ISSUE THREAD

**Issue by nhooyr** [github/hub#1835]
I'm writing a tool to synchronize a standard set of labels across my repositories as GitHub has not implemented this feature yet. I'm using https://github.com/google/go-github

I was thinking about how to deal with authentication when I realized this package already exports 

https://github.com/github/hub/blob/c60ca203c9ecfdb8e0693a0fc0edfa9d58dd00d1/github/config.go#L301

Which makes it extremely easy to reuse the same authentication as hub itself and so I don't have to implement anything special. This is very convenient. It'd be even better if we added a method to the config struct to return the correct Base and Upload URLs for the APIs. E.g. `api.github.com` vs `exampleenterprisegithub.com/api/v3`. This would make it dead simple to use [google/go-github](https://github.com/google/go-github) with `hub`'s config file and authentication.

If this is approved I can work on PR.

**Comment by mislav** [comment]
Hi there! I like your line of thinking, but I don't think it's a good idea to import methods from hub into other projects since hub wasn't really designed as a library to be embedded. It's likely that hub's source file names and method names will shift around and that your tool to sync labels might break as a result of updating hub. I think it's best that your tool is independent of hub— it will require a tiny bit of extra work from your part initially, but it will prove stabler and easier to maintain in the long run.

**Comment by nhooyr** [comment]
I think it'd be a really neat idea. Would let anyone write a command line tool for Github effortlessly. Its not much effort for hub because the code is already there.

**Comment by nhooyr** [comment]
Do you see the auth code changing?

**Comment by mislav** [comment]
Yes, I see myself restructuring the internal layout of go methods/packages in this repository since I'm not happy how this project is laid out (current packages are large wide in scope)

Anyway, please send me a PR of what you had in mind! But if you end up depending on this library, we're I'm expecting you to keep up with the changes 😉

**Comment by nhooyr** [comment]
I definitely am :P

Will try and do soon. Can you reopen and assign me this issue so I don't forget.

**Comment by mislav** [comment]
I can't assign people from outside the `github` org.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
