### ISSUE TITLE
git hub issue or another command

### ISSUE THREAD

**Issue by AynurFisengi** [github/hub#1836]
This hub command doesn't effect anything? no do the others! I have tried to change the GITHUB_HOST to my companies github web-site. It will always authorisation from me such username and passwort. But it  doesn't change anything. I wait and wait and wait.

Please help me on my issue! 
I always set the HTTP_PROXY.. env variable. 

thanks

**Comment by mislav** [comment]
Hi, I'm not sure where the problem lies, but I don't know your network setup either and how your company uses GitHub Entreprise. You can set `HUB_VERBOSE` to output extra debugging information:

```
HUB_VERBOSE=1 hub issue
```

The general steps to configure hub for GitHub Enterprise are:

1. If your company's github website is at `https://git.example.com`, then do this: `git config --global --add hub.host git.example.com`;
2. `cd` to a local repository whose git remote (see `git remote -v`) points to a repository under `git.example.com`;
3. Do `hub issue` and give your username and password when prompted. If that doesn't work, you can go online to `https://git.example.com/settings/tokens`, generate a new Personal Access Token, and paste it into `~/.config/hub` file:

```yaml
git.example.com:
- user: AynurFisengi
  oauth_token: YOUR-TOKEN
```

hub shouldn't ask you for authentication every time; only the first time.

**Comment by mislav** [comment]
Closing due to staleness
