### ISSUE TITLE
hub pull-request for multiple git account: Not found .. Are you sure that github.com/.. exists?

### ISSUE THREAD

**Issue by AnthonyWC** [github/hub#1847]
hub pull-request doesn't look like it is compatible with multiple git account setup?

In my case, I defined multiple github account in .ssh (e.g. https://gist.github.com/jexchan/2351996)

So other git command works fine in a git repo with an alternative aliased url, e.g. github.com-personal.  However hub pull-request ignores what is shown in git remote -v and instead query the actual url (e.g. github.com instead of github.com-personal alais)

**Comment by mislav** [comment]
Thanks for sharing your setup! 

hub doesn't support this kind of multiple account setup because hub doesn't use SSH keys for authentication. Only OAuth over HTTPS can be used to access the GitHub API, which hub uses to open pull requests (and perform other operations).

If you want to switch between different users for hub, the easiest way to do it is to generate a separate Personal Access Token, and then use them via a script on the command-line that sets GITHUB_TOKEN environment variable:

```sh
GITHUB_TOKEN="TOKEN-FOR-USER1" hub pull-request ...
GITHUB_TOKEN="TOKEN-FOR-USER2" hub pull-request ...
```

**Comment by AnthonyWC** [comment]
Ok good to know.
