### ISSUE TITLE
`hub create` fails to set the remote `origin` to the newly created repository, despite claiming to do so

### ISSUE THREAD

**Issue by 9999years** [github/hub#1849]
When I create a repository with `git create`, hub fails to set the remote `origin` to the newly created repository, despite claiming to do so.

Is this an error-checking mechanism? Either don’t claim to `set remote origin` or actually change the origin. It might also be worthwhile to print the old origin URL if applicable.

Example:

    $ mkdir test
    $ cd test
    $ git init
    Initialized empty Git repository in C:/Users/arvensis/Documents/projects/test/.git/
    $ git create
    Updating origin
    created repository: 9999years/test
    $ git remote -v
    origin  https://github.com/whatever/test.git (fetch)
    origin  https://github.com/whatever/test.git (push)
    $ git remote set-url origin https://example.com/
    $ git remote -v
    origin  https://example.com/ (fetch)
    origin  https://example.com/ (push)
    $ git create
    9999years/test already exists on github.com
    origin  https://example.com/ (fetch)
    origin  https://example.com/ (push)
    set remote origin: 9999years/test
    $ git remote -v
    origin  https://example.com/ (fetch)
    origin  https://example.com/ (push)

**Comment by mislav** [comment]
Thank you for reporting. Which `hub version` do you have?

A more recent version will not overwrite the `origin` remote if it exists. It would stay at `https://example.com`, but it will also _not_ print `set remote origin: 9999years/test`. To me, this is the desired behavior (i.e. not overwriting URLs of existing remotes). What do you think?

**Comment by 9999years** [comment]
It’s good that a newer version doesn’t erroneously print that it’s setting the origin. I think that’s a good default, but I *would* like an option to overwrite urls; I suppose I could `git remote rm origin && git create` — but something like `git create -f` seems slightly more ergonomic.

Anyways:
```
$ hub version
git version 2.18.0.windows.1
hub version 2.2.9
```

One of my least favorite things about Git is how difficult working with branches and remotes is; I don’t quite understand why `git branch -u origin/master master` isn’t the default case since I’m absolutely positive that’s almost every use of Git — all branches track branches from the same name on remote origin; usually there’s even only one branch! But perhaps that’s out of scope here — see #1848.

**Comment by mislav** [comment]
> One of my least favorite things about Git is how difficult working with branches and remotes is

It can be a pain, yes. Out of curiousity, what is your `git config push.default` setting (if any)?

**Comment by 9999years** [comment]
```
$ git config push.default
current
```

Which explains why pushing but not pulling works. Perhaps a `pull.default` setting is warranted? Maybe something like setting `branch.master.remote` to `origin` will cover most of my cases? I’ll update if I learn anything new.

**Comment by mislav** [comment]
@9999years I think the best setting to learn git with is the default since Git 2.0: `simple`. https://git-scm.com/docs/git-config#git-config-pushdefault

**Comment by vfonic** [comment]
I just noticed the same error.
I'm moving two projects from GitLab.
For the first one, I created the GitHub repo manually (through the GH website). I then ran `git remote add vfonic/the_bestest_project_evah` (while I still had `origin` remote pointing to GitLab). This created a new remote `vfonic` pointing to GitHub.
I then realized there's `hub create` command and I ran `git create` in another repo. This created an empty repo on GitHub and didn't create any remotes (since `origin` is already pointing to GitLab). 
Ideally, there would be -f option, or the CLI might prompt user which remote name to use, when `origin` is already taken (and not pointing to the same GH "correct" repo.
Since documentation is saying the remote will be created, but nothing happens in this case, at least an error message could be printed to the command line. Something similar to the one when GH remote repo already exists: https://github.com/github/hub/blob/24fefa3dcf4ee4a2589d28366bd2fa3975a8bb0c/commands/create.go#L120

Thanks!
