### ISSUE TITLE
Issue create picking the "wrong" remote

### ISSUE THREAD

**Issue by rouzier** [github/hub#1856]
When doing a ```hub issue create``` it will choose the first remote from ```git remote -v``` instead of the remote of the current branch.

**Comment by mislav** [comment]
hub will pick remote names in this order of preference:

1. `github`;
2. `upstream`;
3. `origin`;
4. The first other remote that it finds.

It will pay no special attention to the remote that the current branch points to.

Solution: have the `github` or `upstream` remote point to the canonical version of this repository on GitHub against most API operations (such as opening issues/PRs) should be performed.

**Comment by rouzier** [comment]
Would you accept a pull request that would first check the environmental variable HUB_REMOTE?

**Comment by mislav** [comment]
I don't think an environment variable is the best interface. I envisioned global flags such as `--remote` and `--repo` that could be used for any hub command to affect the remote used per-invocation. https://github.com/github/hub/pull/1342#issuecomment-261533133

If a default remote needs to be specified across all commands, that could be achieved with global config feature. https://github.com/github/hub/issues/964

All of these features were planned for a long time but because of their scope, I didn't yet have time to implement them.

Closing this out in favor of the aforementioned existing threads. Please subscribe to them for updates!
