### ISSUE TITLE
Dependent Pull Requests

### ISSUE THREAD

**Issue by dabrahams** [github/hub#1890]
Even if Github never gets around to implementing support for [this long-standing feature request](https://github.com/isaacs/github/issues/959), hub could implement all the important elements from the command line, tracking the necessary information in git notes or hidden branches.

**Comment by mislav** [comment]
It could, but this falls a little bit outside of scope of hub because it's too specific to a particular workflow. Hub only implements features that GitHub also supports. Tracking dependent pull requests should be best implemented as a script on its own that can be used in combination with `hub pull-request`.

**Comment by dabrahams** [comment]
Fair enough.  I am looking to implement such a facility and it's useful to know that it doesn't fit in hub.
