### ISSUE TITLE
List Reviewers Set by Hub

### ISSUE THREAD

**Issue by igbanam** [github/hub#1953]
I found that when listing reviewers on a PR, only the reviewers set on GitHub show up with the following command

```
%sC%>(8)%i%Creset %t  %l being reviewed by %rs%n
```

Note that this is the default format with the `being reviewed by` bit.

The reviewers added by hub when creating the PR, like `hub pull-request -r me,you` don't show up when you try to show the reviewers on the PR using `hub pr list -f %rs`. 

I also found that on GitHub, these reviewers show up under the reviewers pane. But when I click the gear icon, they are not ticked (i.e. they do not look like they've been selected)

I would like to be able to set reviewers when creating a PR using hub, and view the reviewers on the PR using hub.

**Comment by mislav** [comment]
Hi thank you for reporting! The `%rs` thing is very new and we might still need to refine the feature.

In https://github.com/github/hub/pull/1924 @Crunch09 points out:

> If instead we want to list all reviewers (not just requested ones) we would need to make additional API requests I think.

And that seems to be true: as soon as a requested reviewer (or team) has actually left a review, they disappear from the "requested reviewers" API payload. So it seems that "requested reviewers" here means the reviewers that were requested _but who haven't actually left a review yet_, rather than a static list of initially requested reviewers.

This API detail makes `%rs` less useful, in my opinion. But to fix it, we would have to make a separate API request per each individual PR in the list. In a big list, that would make the response very slow.

How do you (and other readers of this thread) expect this feature to work?

**Comment by igbanam** [comment]
Ah, I see. Making the argument for https://developer.github.com/v3/pulls/reviews/#list-reviews-on-a-pull-request for each PR on a huge list isn't quite wise right now, seeing that the list of users from this response should be melded with the list of "requested reviewers" for this to be complete.

I would leave this open though, in hopes that the technology behind would better align in the future

**Comment by mislav** [comment]
After some consideration, I have decided that—for now—this is best implemented in user scripts, rather than maintained in hub core. Now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3

Thank you for suggesting!
