### ISSUE TITLE
Newline needed after output.

### ISSUE THREAD

**Issue by alexfornuto** [github/hub#1972]
## Issue
After asking hub for an issue URL or title, the response does not include a new line. This puts the next CLI prompt on the same line, affecting the formatting of the response.

### Example

```bash
USER@HOSTNAME ~/repos/documentation/source/_docs (master) $ hub issue show -f %U 3815
https://github.com/pantheon-systems/documentation/issues/3815USER@HOSTNAME ~/repos/documentation/source/_docs (master) $ hub issue show -f %t 3815
Cloudflare Domain Configuration Doc Update USER@HOSTNAME ~/repos/documentation/source/_docs (master) $ 
```

In the example above, the URL I asked for bleeds into the next bash prompt, so I can't just CTRL+click on it.

## Resolution
Update the issue command so that all `-f` formats requested return a `\n` after the output (unless being piped to a file I suppose).

## System
OS: Fedora 29
git version: 2.19.2
hub version: 2.6.0

**Comment by mislav** [comment]
The `hub help issue` documentation says that the default format string is `%sC%>(8)%i%Creset %t% l%n`. Notice the `%n` in the end. The documentation also suggests to look up "PRETTY FORMATS" section of git-log(1). In there, `%n` is documented as a newline. The solution is to append `%n` if you want a newline.

However, since this might not be clear from hub's own documentation, I'm going to amend the docs to point this out.

**Comment by alexfornuto** [comment]
Thanks @mislav  - I think an entry for `%n` under the documentation for `-f` would suffice, and I'd be happy to make a PR adding it.
