### ISSUE TITLE
Git can not ignore already exists file

### ISSUE THREAD

**Issue by moonknight37** [github/hub#2006]
I have a properties file which contains configuration of the formal environment on the Github server. I changed the file on my local machine for the test environment. When I try to pull file, the Git client always prompt me to merge the change, but the file on server can not be change .

**Comment by mislav** [comment]
Hi, I believe this is a question about GitHub.com, the website. This issue tracker is for a command-line utility called `hub`, not the website itself. For reporting bugs and requesting features for GitHub the website, please email support@github.com. This also sounds like a git usage question, so it might be best suited to ask at a site like Stack Overflow rather than at our support. Thank you!
