### ISSUE TITLE
Please improve error message to be specific

### ISSUE THREAD

**Issue by ralphrmartin** [github/hub#2010]
While using cask-repair -d from homebrew, I got multiple messages of the form
```
ERROR: Repository not found.
fatal: Could not read from remote repository.

```
The author of that command tells me these were issued by hub.
Unfortunately, they are rather unhelpful, as they do not tell the user which repository has not been found.
Could they please be improved to include the name of the repository which could not be found?

**Comment by mislav** [comment]
I'm not sure if this error message comes from hub. Could you retry running cask-repair with `HUB_VERBOSE=1` and see if hub outputs any extra debugging information? Please scrub sensitive information and paste the relevant output here. Thank you!

**Comment by ralphrmartin** [comment]
Sorry, but I have fixed the underlying error which caused the message now. However, the author of cask-repair assures me his software is not producing the message, and suggests that hub is responsible.

As for versions:
git version 2.20.1
hub version 2.7.1

**Comment by mislav** [comment]
hub source code doesn't have any error message that includes "repository not found":

```
~/p/go/src/github.com/github/hub (master) $ ag 'repository not found'
features/release.feature
218:  Scenario: Repository not found when listing releases
```

git itself, however, does produce this message on invalid push:

```
$ git push https://github.com/mislav/nonexist.git master
remote: Repository not found.
fatal: repository 'https://github.com/mislav/nonexist.git/' not found
```

Hub does not handle nor affect any of the git network operations such as pushing/pulling. This suggests that the bug is in how cask-repair invokes git.

**Comment by ralphrmartin** [comment]
Thanks. I'll raise with git

**Comment by mislav** [comment]
Just to be clear: I do not think that the bug is in git itself, so don't take my words as advice to file a bug with the git project. I'm fairly convinced that the bug is in the `cask-repair` script either creating some faulty state on your system or was unable to deal with an edge case that was specific to your system. If you encounter this again, please invest some time in debugging in the interest of gathering more data before opening bug reports. 🙇
