### ISSUE TITLE
[Feature] Allow `branch` to add protections

### ISSUE THREAD

**Issue by billmoritz** [github/hub#2024]
`branch`

It would be helpful to be able to add protections to a branch from the command line. I noticed #1548 states that administration features are outside the scope of this project. I would be happy to work on this here or in another Github sponsored project.

**Comment by mislav** [comment]
Hi, hub aims mostly to encapsulate workflows that are a more daily part of working with GitHub, like cloning repos, viewing issues, opening pull requests, etc.

Branch protections are best managed through the GitHub web interface, but if you want to do it from the command-line, you can use the new `hub api` command to make requests against any API endpoint, e.g.:

```sh
hub api -t hub api repos/{owner}/{repo}/branches/master/protection
```

I'm not sure if `hub api` covers all the functionality necessary to implement this, but you can try and find out. It looks to me like branch protections is a pretty complex API that sometimes expects nested JSON objects in the payload such as hashes and arrays. `hub api` still doesn't support those, but we could add support to facilitate that.

In any case, even if you do implement this on top of `hub api`, I would suggest that you maintain this in your own separate repo, since this is too large in scope to be maintained under this repo.

**Comment by billmoritz** [comment]
I will find another tool to do this work. Thanks @mislav.
