### ISSUE TITLE
release isn't using latest master nor -t flag

### ISSUE THREAD

**Issue by Schizo** [github/hub#2043]
I might be using this wrong, but I wanted to create a release with the latest master, so I've tried

    hub release create -m "Automated release" release

That used an older commit that was 30 commit's behind. So I tried the `-t` and put a commit sha

    hub release create -m "Automated release" -t HASHOFCOMMIT release 

That still didn't work, am I doing something wrong?

**Comment by mislav** [comment]
According to `hub release --help`:

```
release create [-dpoc] [-a <FILE>] [-m <MESSAGE>|-F <FILE>] [-t <TARGET>] <TAG>
```

You are passing `release` as a value for `<TAG>`, is that intentional? Tags are usually in the format of `v1.2.3` or similar.

`<TAG>` should either already exist as a git tag in your remote repository, or it will be created. If you pass `-t <TARGET>` (branch name or SHA), the tag will be created on `<TARGET>`; otherwise it will be created on the latest state of the default branch (usually `master`) as it is currently in the remote repository.

Was all this unclear? Could the docs be improved?

**Comment by Schizo** [comment]
Thanks for your reply. The discrepancy came from the workflow we manage tag's and our wrong assumptions that `hub release delete tag` will delete the release and as well the tag that it created before. 

1) `hub release create -m "test" test` will create a tag `release` and create a release
2) `hub release delete tag` will delete the release but keep the tag

So as the tag was already created, any new release would just point to the tag that was created beforehand.

**Comment by mislav** [comment]
Ah I see; thank you for following up!

> our wrong assumptions that `hub release delete tag` will delete the release and as well the tag that it created before.

Ouch, that sounds like something that could be a common pitfall. However, I'm reluctant to automatically clean up the git tag as well after `hub release delete` because we don't know at this point whether the tag was auto-created with the release, or has it existed before. If it had existed before, it would be wrong to delete it. 🤔 

For now I've just pointed this out in our documentation.

**Comment by Schizo** [comment]
As long as it's part of the documentation it should be fine, the `create` tag was very verbose, if the `delete` one point's that out too, that would be great. I'm too not pleased about automatically deleting a tag, that might not have been created by `hub`

> Create a GitHub release for the specified TAG name. If git tag TAG does not exist, it will be created at TARGET (default: current branch).

Thanks!
