### ISSUE TITLE
[Feature Request] Decline pull request

### ISSUE THREAD

**Issue by ivanskodje** [github/hub#2075]
You would benefit greatly from being able to decline a pull request in a CICD environment.

In an automated system, you may want to perform various tests upon receiving a new pull request, and then decline it if it fails. 👍

**Comment by mislav** [comment]
Hello thanks for writing in. I would like a few clarifications?

1. Is this about GitHub (the website/platform) or `hub` (the command-line tool)?
2. What is a CICD environment and how is it relevant here?
3. How does "declining" a pull request manifest itself? Does the PR get closed, or something else?

**Comment by ivanskodje** [comment]
> Hello thanks for writing in. I would like a few clarifications?
> 
> 1. Is this about GitHub (the website/platform) or `hub` (the command-line tool)?
> 2. What is a CICD environment and how is it relevant here?
> 3. How does "declining" a pull request manifest itself? Does the PR get closed, or something else?

1. This is about using the hub command-line tool to remotely decline pull requests
2. Github webhook -> Jenkins -> Build, Test, Deploy. Jenkins should be able to use the `hub` command-line tool to decline the pull request if it fails during testing. 
3. Good question. It would be very beneficial to be able to decide whether or not you want to close PR, ask for change, or accept the change. For my own use, I would probably only use it to request a change instead of closing the PR completely.

**Comment by mislav** [comment]
Thank you for the clarifications. It sounds like you want to run some CI checks for every Pull Request (or subsequent push to a PR), and "decline" (i.e. mark as "failed") the PR if any of the checks failed. GitHub has features precisely for that; see https://help.github.com/en/articles/about-status-checks

If you need to interface with the GitHub API directly from the command-line (for example, to write to the Statuses API), you can use [the `hub api` command](https://hub.github.com/hub-api.1.html). For example, in your CI job you could do:

```sh
GITHUB_TOKEN=<your-oauth-token> hub api repos/{owner}/{repo}/statuses/<SHA> \
  -f state=failure \
  -f context=my-check
```

However, doing any API integration like this is left as an exercise to the reader; at the current time we will not create features for updating the Statuses or Checks API in hub since that falls outside of the scope of the project.
