### ISSUE TITLE
How to delete a release asset tarball with hub api (if possible?)

### ISSUE THREAD

**Issue by mathomp4** [github/hub#2114]
All,

I love `hub` and use it quite a bit at the "naive user" level. I can `hub issue`, `hub create`, etc. 

However, a colleague has an interesting puzzle. He made a "pre-release" with a tag and GitHub gladly autogenerated tarballs that turned out to be bad (`git --archive` didn't include some submodule metadata, see https://github.com/Goddard-Fortran-Ecosystem/pFUnit/releases/tag/v4.0_beta). 

What he'd like to do is delete those tarballs and re-upload new ones with the fixes needed.

I know `hub` recently added the `hub api` ability. I also see from this page: https://developer.github.com/v3/repos/releases/#delete-a-release-asset that there might be a way to remove single assets. I'm just not sure how to translate that into command line speak. I figure if I can do it once, I'll know, but getting to that point is daunting. 

I know this gets me at least to the release:
```
GITHUB_HOST=github.com hub api -t repos/Goddard-Fortran-Ecosystem/pFUnit/releases/16609896
```
And it only took me like two hours to get that working. :smile: But now I'm way out of my league.

Help?

**Comment by mislav** [comment]
Hello! Good question. To list all assets for a release:

```sh
hub api -t repos/{owner}/{repo}/releases/16609896/assets
```

This lists all uploaded assets, and they each have a `url` property. You can then DELETE that asset:

```sh
hub api -X DELETE "$asset_url"
```

Keep in mind that you probably can't delete the auto-generated zipball + tarball because they were never uploaded either. If there's a problem with those, you should report it to support@github.com and, in the meantime, manually upload a new tarball that people should use. The manually uploaded assets appear _above_ the auto-genearted ones in our UI.
