### ISSUE TITLE
Add a hub command to jump to a particular file in the browser

### ISSUE THREAD

**Issue by rlipscombe** [github/hub#2121]
If I'm somewhere in my working copy, and I `hub goto relative/path/to/some_file.ext`, it would be _super_ cool if hub could open my web browser at the relevant file, in the relevant branch of the relevant repo.

That way, I can grep (or ack, or ag) around in my working copy, and then I can easily get hold of a github URL for the matched file that I can paste into Slack.

**Comment by mislav** [comment]
This is [already on our roadmap](https://github.com/github/hub/projects/1)! I will close the issue since we're already tracking this.

We want to improve `browse` so it handles opening commits and files in an easier way. We will most likely make it a new command and deprecate `browse` in favor of that.

In the meantime, you can do this:

```console
$ git config --global alias.goto '!bash -c "hub browse -- blob/\\$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)/\\$1"'
$ git goto path/to/file.ext
```
