### ISSUE TITLE
Adding a milestone to issue

### ISSUE THREAD

**Issue by daniel-vera-g** [github/hub#2155]
From the man page I get:

`  hub issue create [-oc] [-m MESSAGE|-F FILE] [--edit] [-a USERS] [-M MILESTONE] [-l LABELS]`

When I try to open an issue like:

`hub issue create -m "Test" --edit -M v0.0.1 -l feature`

Or:

`hub issue create -m "Test" --edit -M "v0.0.1" -l feature`

with the milestone existing, it creates the issue with the label but without the Milestone.

I am using: 

```
git version 2.21.0 
hub version 2.11.2 
```

Did I miss something?

**Comment by mislav** [comment]
It seems like `hub issue create -M` expects to receive a numeric ID for a milestone rather than its title suh as `v0.0.1` https://github.com/github/hub/blob/d76e3e8ebf5a37eb13dc820dc42a3262f9be6db3/commands/issue.go#L577-L579

`hub pull-request` is better because it also accepts milestone titles https://github.com/github/hub/blob/d76e3e8ebf5a37eb13dc820dc42a3262f9be6db3/commands/pull_request.go#L305-L315

I wasn't aware that these commands treat milestones differently. Would you like to submit a PR that extends the same approach that `hub pull-request` has to `hub issue create`?

**Comment by daniel-vera-g** [comment]
Ah ok.

I am not really fluent in go, but will try to submit the PR in the course of this week.

**Comment by mislav** [comment]
Fixed in https://github.com/github/hub/pull/2166
