### ISSUE TITLE
Download Organisation

### ISSUE THREAD

**Issue by ShalokShalom** [github/hub#2165]
I am working on a project that uses hundreds of repositories. Other solutions such as https://github.com/tegon/clone-org-repos have not worked yet. I think that could fit very nice in here. :hugs:

**Comment by mislav** [comment]
Hello, I don't think you've explained your use-case really clearly (what does "downloading an organization" really mean?), but I'm guessing that you want to clone all repositories within an organization. This was requested before https://github.com/github/hub/issues/1617, and hub won't provide this simply because I think such a feature will see very little use.

You can achieve this manually by using `hub api` to first get the list of all repositories owned by a user/organization. The trickiest part will be paginating over all results if there are a lot of repositories. Example script:

```sh
repos() {
  local owner="${1?}"
  shift 1
  paginate hub api -t graphql -f owner="$owner" "$@" -f query='
    query($owner: String!, $per_page: Int = 100, $after: String) {
      repositoryOwner(login: $owner) {
        repositories(first: $per_page, after: $after, ownerAffiliations: OWNER) {
          nodes {
            nameWithOwner
          }
          pageInfo {
            hasNextPage
            endCursor
          }
        }
      }
    }
  '
}

paginate() {
  local output cursor
  output="$("$@")"
  if [[ $output == \{* ]]; then
    cursor="$(jq -r '..|.pageInfo?|select(.hasNextPage)|.endCursor' <<<"$output")"
  else
    cursor="$(awk '/\.hasNextPage/ { has_next=$2 } /\.endCursor/ { if (has_next=="true") print $2 }' <<<"$output")"
  fi
  printf "%s\n" "$output"
  [ -z "$cursor" ] || paginate "$@" -f after="$cursor"
}

# clone all repos owned by "octocat"
repos octocat | awk '/\.nameWithOwner/ { print $2 }' | while read repo; do
  hub clone "$repo"
done
```

**Comment by ShalokShalom** [comment]
I guess this will see not very often usage, while when, is it super annoying to do so currently.
