### ISSUE TITLE
is it possible to add a note to a github project using hub?

### ISSUE THREAD

**Issue by seiyria** [github/hub#2170]
For example, if I wanted to just add a text entry to a project like this one https://github.com/github/hub/projects/1 - is it possible to do something like `hub project -i 1 -t "this is sample card text"`?

**Comment by mislav** [comment]
No, project management features are not implemented by any of the hub commands. You can use the lower-level `hub api` command to [programmatically create cards](https://developer.github.com/v3/projects/cards/#create-a-project-card):

```
hub api -H "Accept: application/vnd.github.inertia-preview+json" projects/columns/:column_id/cards -f note="this is sample card text"
```

The custom "Accept" header is because this API is in a preview phase.

Of course, to find out the `:column_id` you would first have to [query other APIs](https://developer.github.com/v3/projects/columns/#list-project-columns) too. So it's not really a one-liner, it would have to be a bit of scripting. But it could be done.

Right now this is not something we plan to cover in hub core, though.

**Comment by seiyria** [comment]
Thanks for the response!
