### ISSUE TITLE
Display more informative `pull-request` error when head repository is not a fork

### ISSUE THREAD

**Issue by adamsigal** [github/hub#2173]
I forked a specific repository, and even though the root git node was the same (and correct) GitHub didn't display "forked from". The internal problems associated with this caused me to be unable to create a pull request, giving me the following error:

```
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
```

/cc @purpleidea

**Comment by mislav** [comment]
@adamsigal I'm sorry you're having trouble. If GitHub doesn't think that your repo is a fork (evident by the lack of "forked from"), then there's nothing we can do from `hub pull-request` since opening a PR from your “fork” is impossible.

This is not something I can solve from `hub`. You will need to write to support@github.com or https://github.com/contact. You will have to provide them with specific links to repos in question. Good luck!

**Comment by purpleidea** [comment]
@mislav It's quite true that it's probably GitHub who is to blame, because they require you to use their proprietary API to create the fork instead of looking at the git root nodes to determine that they are "peers". This should as you mentioned, be reported upstream.

However, figuring out that this was the problem that `hub` wasn't working, was not obvious and I had to figure it out myself. It would be excellent if the tool would detect this scenario and display a more useful error message. In particular because this is a commonly seen error message and it's indistinguishable from the other situations.

Could you please re-open (and rename this issue if necessary) until the error message is clearer?

Thanks!

**Comment by mislav** [comment]
@purpleidea Good point; thank you!

**Comment by mislav** [comment]
@purpleidea Actually I'm going to reopen your original issue https://github.com/github/hub/issues/1786

**Comment by purpleidea** [comment]
@mislav :man_facepalming: I knew this felt familiar. Thanks for noticing/opening.
