### ISSUE TITLE
Set BROWSER in OSX

### ISSUE THREAD

**Issue by alexsapran** [github/hub#2178]
Hi all, 

I am trying to figure out how to open in Google Chrome when issuing `hub browse` in OSX, while I do not want to open the default browser. 
The current problem with OSX is that for example Google Chrome is located under the path 
`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome` (note the spaces)
Now if I set the env variable `$BROWSER` I can see hub is picking this up but it fails to locate the binary due to space. 
 
```
↳$ BROWSER='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'  HUB_VERBOSE=1 hub browse
$ git rev-parse -q --git-dir
$ git remote -v
$ git config --get-all hub.host
$ git config push.default
$ git rev-parse -q --git-path refs/remotes/origin/pr/xxx
$ git rev-parse -q --git-path refs/remotes/upstream/pr/xxx
Unterminated backslash-escape
```
and 

```
↳$ BROWSER='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'  HUB_VERBOSE=1 hub browse
$ git rev-parse -q --git-dir
$ git remote -v
$ git config --get-all hub.host
$ git config push.default
$ git rev-parse -q --git-path refs/remotes/origin/pr/35230
$ git rev-parse -q --git-path refs/remotes/upstream/pr/35230
$ /Applications/Google Chrome.app/Contents/MacOS/Google Chrome https://github.com/xxxx/yyyyyy
exec: "/Applications/Google": command not found
```

Any idea on what I am doing wrong or if I should be calling hub in another way?

**Comment by mislav** [comment]
You're not doing anything wrong, this seems broken. 

It's due to us splitting BROWSER with a space to support extra arguments being passed to a browser https://github.com/github/hub/blob/de6f95cc0707d80bd569804608bf618f38ca681b/utils/utils.go#L39

We should probably do shell-compatible word splitting https://github.com/github/hub/blob/de6f95cc0707d80bd569804608bf618f38ca681b/cmd/cmd.go#L127

so that you will be able to do `BROWSER='"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --any --extra --arguments'`.

For now, this might be the only solution: save this script somewhere in your PATH and make it executable:

```
#!/bin/sh
exec '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' "$@"
```

Then set the name of that script as BROWSER.

**Comment by alexsapran** [comment]
ya, that seems to work, thanks so much for the quick replay and providing the workaround
