### ISSUE TITLE
Add marketplace action release

### ISSUE THREAD

**Issue by elgohr** [github/hub#2223]
It would be cool, if `hub` could also create [marketplace releases](https://developer.github.com/marketplace/actions/publishing-an-action-in-the-github-marketplace/).
Sadly I don't know an official API for that. Otherwise I would have created a PR.
Would it be ok to add it by inofficial API (reverse engineering)?

**Comment by mislav** [comment]
You are welcome to use `hub api` manually to access any published (or in public beta) GitHub API be it REST or GraphQL, but I wouldn't recommend using any unofficial APIs.

We will not bake any Marketplace/Actions features into hub core right now since I feel it is too early to be implementing those on the command-line and because it doesn't fit the problem space that hub right now aims to solve (make every-day work with GitHub repos easier).
