### ISSUE TITLE
Issue transferring

### ISSUE THREAD

**Issue by mlewand** [github/hub#2252]
Not that long ago GH added a feature to transfer a single issue.

It would be nice to add this feature in `hub` binary too.

I guess the basic syntax might looks something like:

```
hub issue transfer NUMBER TARGET_REPO

# e.g.
hub issue transfer 123 myUser/newRepo
```

My use case is that I'm centralizing issue tracker for multirepo architecture. So I want to use `hub` binary to move a ton of issues to another repository.

**Comment by mislav** [comment]
This is a good feature idea. I thought that it wasn't possible to transfer issues using the GitHub API, but as it turns out this is possible using the GraphQL API, so I have written a `hub api` wrapper script to demonstrate how you can programatically do this today: https://github.com/mislav/hub-api-utils/blob/master/bin/hub-issue-transfer

Note that if you're transferring issues in bulk, you can probably edit that script to also look up issue/repository node IDs (needed for the `transferIssue` mutation) in bulk, which would potentially speed up the overall script.

Since I believe all this should be simpler and potentially baked into hub, I will keep this issue open as a feature request. In the meantime please use `hub api` to programatically achieve what you need and let me know if you encounter any issues.

**Comment by mlewand** [comment]
Amazing, thank you for the input @mislav.

**Comment by srafi1** [comment]
Is anyone working on this? If not, I'd like to give it a shot.

**Comment by mislav** [comment]
@srafi1 Go ahead! 👍

**Comment by mislav** [comment]
This was implemented 🙇 🏆 https://github.com/github/hub/commit/4c2e44146988dfb385a26f649298f274a5017756
