### ISSUE TITLE
Locally merge from one branch to another

### ISSUE THREAD

**Issue by pascalandy** [github/hub#2253]
Here is something I do all the time locally using Tower 2. 

- branch **master** to **edge**
- do changes on **edge** + commits
- I want to merge into to **master**, then
- checkout to **master**
- merge **edge** into **master**
- push commits
- done

May it's basic git stuff but I don'T know how to do it.

### see videocast

https://cl.ly/64641abbe1f3

**Comment by mislav** [comment]
Hello @pascalandy, yours seems like a question about regular git usage and not something specific to the hub project, and since this is an issue tracker for `hub` functionality, I will close this.

For learning git on the command-line, I suggest that you ask elsewhere, such as on Stack Overflow forums.

For what it's worth, the steps that you describe above may be achieved like this in git command-line:

1. (on "master")`git checkout -b edge`
1. (after changes) `git commit -am "made changes"`
1. `git checkout master`
1. `git merge edge`
1. `git push`
1. done.

Good luck!
