### ISSUE TITLE
feature request: change default for -f

### ISSUE THREAD

**Issue by rayjlinden** [github/hub#2265]
It would be nice if one could change the default template used for a given command that has the -f option (hub pr list, hub ci-status).

For example, we typically want to do pr list - but we almost always want to get the pr url which is not in the default.  It would be nice if I could override the default format used by setting a value in the config file.  (-f would still override the default)

**Comment by mislav** [comment]
Good idea! An old issue #964 proposed exactly something like this: a way to specify default flags for a command. In that thread we also talked about the possibility to specify default flags per-repo (i.e. only in the current project) and globally (i.e. for any hub commands run for the current system user).

The reason why that issue is still open is because I haven't had time to dive into implementing this feature, but it's definitely on our roadmap. I will close this in favor of the referenced issue.
