### ISSUE TITLE
ci-status won't work with 7-digits commit SHA

### ISSUE THREAD

**Issue by joshuabezaleel** [github/hub#2266]
I tried to run ```hub ci-status``` with the short version of the commit SHA but it won't work. The commit that I am going to refer to can be found [here](https://github.com/github/hub/pull/1705/commits/e039ab02669ab9f2559458ad52296ee762563dee).

command: ```hub ci-status e039ab0```
output: ```Aborted: no revision could be determined from 'e039ab0'```

command: ```hub ci-status e039ab02669ab9f2559458ad52296ee762563dee```
output: ```failure```

**Comment by mislav** [comment]
Hub resolves the short SHA using `git rev-parse -q SHA`. It looks like the SHA you pasted could not be resolved in my local git repo, and neither in yours it seems. It might be because it's coming from a fork and not the main repo?

How would you expect `e039ab0` to be resolved in this case?

**Comment by joshuabezaleel** [comment]
I am sorry beforehand, I forgot which PR is that commit SHA from.
Let's just say we take the example of [this PR](https://github.com/github/hub/pull/2298).
The [latest commit](https://github.com/github/hub/pull/2298/commits/d7de991be83337de2d5b8dce29c6cd7b6f0a8bd5) has the long SHA of `d7de991be83337de2d5b8dce29c6cd7b6f0a8bd5` and the short 7-digit SHA of `d7de991`.

I attached the screenshot below that the `hub ci-status` command works with the long version of the SHA but not with the short version of the SHA. Is this the expected behavior?

Thank you very much! :slightly_smiling_face: 

![image](https://user-images.githubusercontent.com/7043511/66476550-15b03280-eac0-11e9-921d-edcf3a03854d.png)

**Comment by mislav** [comment]
> I attached the screenshot below that the `hub ci-status` command works with the long version of the SHA but not with the short version of the SHA. Is this the expected behavior?

It may be surprising, but I think this is expected behavior. Our local git repos cannot resolve the short SHA into the full commit ID because they don't contain that commit; it comes from a fork. (The commit would be resolved if we pulled from that specific fork.)

When using the full commit ID, it is passed unchanged to the API and it is found there.

The general rule is that it's usually better to use full commit SHAs rather than short ones. If you use short ones, you should ensure that your local git repo can resolve them to something.

Does this make sense?

**Comment by joshuabezaleel** [comment]
Ah now that make sense. Sorry for the question.
Thank you for the explanation! :slightly_smiling_face: I am goign to close this Issue then.
