### ISSUE TITLE
Specify label in file for issue creation

### ISSUE THREAD

**Issue by evanfreed** [github/hub#2268]
I commonly create multiple (50-100) issues from a set of (local) markdown templates all of which might have a unique set of labels associated.  I currently use a bash loop to create all of these which may not be the most effective, but it works.  I think a nice feature when creating an issue from a file would be if there was a way to specify labels in the file instead of inline with the `hub issue create` command

(using <> for lack of a better way to specify)
```
# myfile.md
This is my title

<label>infrastructure</label>
<label>bug</label>

This is the description of my issue
```

This would be the same as performing

```
hub issue create -F "myfile.md"  -l infrastructure,bug
```

**Comment by mislav** [comment]
Interesting use case; thank you for describing.

This is a sort of feature that I don't see supporting in hub mostly because it's too specific and I don't think it would see wide use. But if you already use a bash script to create these issues in bulk, and hub is designed to be highly scriptable, then I suggest a script approach kind of like the following:

`myfile.md`:
```
This is my title

/label=infrastructure
/label=bug

This is the description of my issue
```

and the script itself:

```bash
extract_labels() {
  grep '^/label=' | cut -d= -f2 | tr $'\n' ','
}

clear_labels() {
  sed '/^\/label=/d'
}

for file in *.md; do
  clear_labels <"$file" | hub pull-request -F- -l "$(extract_labels <"$file")"
done
```

My rationale for this approach is: if you're already making a script, then you can handle some of these custom tasks through scripting rather than hub having to support them internally.

I'm going to close this issue, hoping that it solves your case. Let me know of further thoughts!
