### ISSUE TITLE
no instructions to install hub on centos

### ISSUE THREAD

**Issue by ssbarnea** [github/hub#2278]
no instructions to install hub on centos

**Comment by mislav** [comment]
We don't cover any possible platform in our installation instructions. Installation on any Linux is always possible by downloading precompiled binaries or building from source; both of which are already covered in the documenation. If someone wants to contribute installation instructions specific to Centos, they are welcome, but I will not keep this issue open in the meantime in order to keep the backlog cleaner. Thank you!

**Comment by ssbarnea** [comment]
I am surprised how far people go to keep backlog clear (in general), maybe we should remind  that **project issue tracker is not the same thing as product backlog**. It would be ok to keep tickets open forever, especially if they are about missing product features. Closing a ticket sends a clear message that does **not** invite people to implement that feature.
