### ISSUE TITLE
hub doesn't work with custom github

### ISSUE THREAD

**Issue by sahil-bawa** [github/hub#2282]
We have our company github server installed for internal use.
The server name is github.<company-name>.corp

I follow the documentation provided here: https://hub.github.com

I run the following commands:
_$ git clone git@internal-git-repo-url
$ hub fork --remote-name=origin
$ git push origin feature
$ hub pull-request_

and get the following error:
**Aborted: could not find any git remote pointing to a GitHub repository**

however, when i run git remote, I see:
_$ git remote_
**origin**

Is there a setting that I can do to enable hub to work on  my internal git server?
If it is an administrative task, I can ask the admin to do it- but I would need information regarding what to do- internet hasn't been kind so far. :(

Sahil Bawa

**Comment by aemonge** [comment]
Same here:

```
$> tail -4 ~/.gitconfig 
[user]
        name = aemonge
[hub]
        host = github.*******.corp
~/wsr/catalog (master)
$> hub clone aem-media
github.com username: ********
github.com password for ******* (never stored): ******
Error cloning repository: Unauthorized (HTTP 401)
Bad credentials
~/wsr/sgt-omnichannel-proyects/API_usa_global_api/catalog (master)
```

**Comment by jasonk** [comment]
> Same here:
> 
> ```
> $> tail -4 ~/.gitconfig 
> [user]
>         name = aemonge
> [hub]
>         host = github.*******.corp
> ~/wsr/catalog (master)
> $> hub clone aem-media
> github.com username: ********
> github.com password for ******* (never stored): ******
> Error cloning repository: Unauthorized (HTTP 401)
> Bad credentials
> ```

This isn't the same, this is an entirely different problem.  This probably means that your GitHub Enterprise instance is using OAuth or SAML or some other external authentication system.  If that's the case then you can't use passwords to authenticate (because GHE doesn't have access to the passwords to verify it).  You have to create a Personal Access Token and use that instead of the password.

**Comment by aemonge** [comment]
Well......
I got confused since the out-put is asking for a githbub.com credentials, not my github.****.corp credentials.

But I'll try your solution and you know.

Thanks !

**Comment by mislav** [comment]
@aemonge `hub clone` will always try to clone from github.com by default, even if you've correctly configured another GHE host. This is because `hub clone` doesn't not know from which host do you intend to clone a repo, so it defaults to github.com.

Use `GITHUB_HOST=github.***.corp hub clone` to set another default.
