### ISSUE TITLE
Bad credentials error

### ISSUE THREAD

**Issue by dmmeteo** [github/hub#2294]
I removed tokens(Settings > Developer settings > Personal access tokens) for hub app. After that I have error message for many commands:
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}

How to fix this?

**Comment by mislav** [comment]
Sorry that you're having trouble. Since you've deleted the token from your GitHub account, if you still want to use some `hub` commands, you will have to re-authenticate.

You can either delete your `~/.config/hub` file, or edit the file to delete the `oauth_token` line containing your old token.

This error message will be better handled after #225 ships. Ideally, hub will detect that your credentials are invalid and offer you to re-authenticate without you having to edit tokens yourself.

**Comment by jackismoe** [comment]
changing the `hub` file works perfectly
