### ISSUE TITLE
Exit status 0 on failure

### ISSUE THREAD

**Issue by nijel** [github/hub#2358]
**Command attempted:**
`hub log -n 1 --format=format:%H @{upstream}`

**What happened:**
```
# hub log -n 1 --format=format:%H @{upstream}
runtime/cgo: pthread_create failed: Resource temporarily unavailable 0731f7e5e43f490c39e364e43988a59ee2be9576
# echo $?
0
```

It seems that the thread creation failure is somehow handled as the command worked in the end, but produced additional output due to that. I'd expect either the error to be propagated as exit status or handled silently without messing up the output.

**More info:**
git version 2.11.0
hub version 2.2.9

**Comment by mislav** [comment]
Thank you for reporting!

Do you have more insight into how the “pthread_create failed” condition might have happened? I'm not familiar with that error, and since `hub log` is simply proxied to `git log` and [we use Exec](https://github.com/github/hub/blob/f4c25a46be716034d9f524709960360ba8188669/cmd/cmd.go#L121) to replace the hub process with the git one, I'm wondering whether this is a bug with Go rather than with hub.

Finally, 2.2.9 (and thus the Go version that it's compiled with) [is 3 years old](https://github.com/github/hub/releases/v2.2.9), and if this keeps giving you trouble, can you try with the newest release?

**Comment by nijel** [comment]
The server was under heavy pressure back then, so it's likely it was running out of memory.

I will try upgrading, actually it's on my todo for some time

**Comment by mislav** [comment]
@nijel I'm going to close this as something that we don't have to necessarily fix with hub. The binary you were using was old and it's possible that this was fixed in newer releases of Go, and also this issue only arises when the current machine is under heavy load, so I doubt that users will run into this.
