### ISSUE TITLE
unable to install hub via apt-get

### ISSUE THREAD

**Issue by meyn** [github/hub#2359]
**Command attempted:**
sudo apt-get update
sudo apt-get install -y hub

**What happened:**
E: Unable to locate package hub

**More info:**
Ubuntu 16.04.4 LTS

**Comment by mislav** [comment]
Hi, packages other than Homebrew are published and maintained by the community and therefore we have no control over them and we offer no guarantees about them.

Furthermore, in the [Installation section of the README](https://github.com/github/hub#installation) we don't list `apt-get install hub` as a supported method of installation on Ubuntu. So I don't think it should be working out-of-the-box.

Because of all this I'm closing this as expected behavior. Sorry for the trouble. You may download the tarball from our official releases and run the install script:

```
sudo env PREFIX=/usr/local /path/to/hub/install
```

**Comment by sourcevault** [comment]
> Because of all this I'm closing this as expected behavior. Sorry for the trouble. You may download the tarball from our official releases and run the install script:
> 
> ```
> sudo env PREFIX=/usr/local /path/to/hub/install
> ```

Could you please provide more detail on how to manually install `hub`, it is not clear what the steps are.
