### ISSUE TITLE
Add subcommand to list repos for an org

### ISSUE THREAD

**Issue by crertel-axios** [github/hub#2387]
**The problem I'm trying to solve:**
For bash scripting and internal support tooling, it can be helpful to be able to see which repos are actually available for a given Github org. This lets us do things like check to make sure a repo already exists before creating it--which we'd normally catch via status code, but `hub create` doesn't reliably return non-zero status codes in such cases.

So, I'm suggesting a command that would let users see a list of repos that are visible to their authenticated user. 

"visible" means:

* A user's own repo
* A user's fork of a repo
* A source repo in an org the user belongs to
* A forked repo in an org the user belongs to

Obviously we don't want it to include every public repo on Github!

**How I imagine hub could expose this functionality:**

For listing all repos visible by a user (
`$ hub list-repos`

For listing the repos visible by a user for a given org:
`$ hub list-repos --org ORG`

For listing the public repos visible by a user for a given org:
`$ hub list-repos --org ORG --public`

For listing the private repos visible by a user for a given org:
`$ hub list-repos --org ORG --private`

**Comment by mislav** [comment]
Thank you for the detailed feature request. This was requested before, but I see this use-case as scripting, and we already have a generic `hub api` command to help with scripting. Example

```sh
hub api 'orgs/MYORG/repos?per_page=100' --paginate -t | awk '/\.full_name\t/ {print $2}'
```

You can also use [GraphQL for advanced queries](https://github.com/mislav/hub-api-utils/blob/master/bin/hub-repos).

The reason why I'm reluctant to add a new command for this is because people would eventually ask for filtering options, and it would present a maintenance overhead.

Ref. https://github.com/github/hub/issues/1419 https://github.com/github/hub/issues/1617 https://github.com/github/hub/issues/2165

> which we'd normally catch via status code, but `hub create` doesn't reliably return non-zero status codes in such cases.

Ooh good catch. I'd welcome contributions in this direction!

**Comment by crertel-axios** [comment]
Thanks for giving that shell one-liner, but it looks like `hub api` doesn't exist, at least as of hub version 2.7.0.

**Comment by mislav** [comment]
Ah yes `hub api` was added in a later version. Most hub packages for different platforms are maintained by the community and are possibly out of date. v2.7.0 is already a year old.

You can use the "standalone" installation instructions to download & install the latest precompiled binary for Linux.
