### ISSUE TITLE
Support for release message template

### ISSUE THREAD

**Issue by CanRau** [github/hub#2437]
**The problem I'm trying to solve:**

Making release messages easier to reason about,
by for example pre-filling headings and links like a compare link

**How I imagine hub could expose this functionality:**

reading it from `./github/RELEASE_TEMPLATE`

Has been asked on SO as well [release-template-for-github](https://stackoverflow.com/questions/56798253/release-template-for-github).
Even though it's not the most popular question 😅

**Comment by mislav** [comment]
@CanRau Interesting idea, but the reason why we support issue and PR templates is primarily:

1. GitHub supports them too;
2. They are oriented towards users who are opening issues/PRs by hand, and they could often use some guidance.

I'm not sure if the same use-case applies to releases too:

1. GitHub doesn't support release templates;
2. Releases can only be created by maintainers of the project, often via scripts/automation, and because of that "templates" such as a shared header/footer or pre-filling headings/links for releases could easily be encoded via scripts/automation.

For instance, this is an example release script that a team could use:

```sh
set -e
cp ./github/RELEASE_TEMPLATE.md ./tmp/release.md
vim ./tmp/release.md # fill in release notes
hub release create v1.0.0 -F ./tmp/release.md
```

**Comment by CanRau** [comment]
I see, yea that example looks useful I think and maybe I can soonish automate even further.
Thanks for the quick explanation and possible solution, very kind 🙏 👍

**Comment by CanRau** [comment]
That's actually pretty slick, didn't even know you could use vim (or nano) as a prompt like this 🎉 👍
