### ISSUE TITLE
`hub create` returns 403 but I have valid permissions.

### ISSUE THREAD

**Issue by karthikskumar** [github/hub#2438]
I'm trying to create a new repo in my organization where I'm not the admin.

When I try `hub create ORGNAME/REPONAME` post initialization I get a message:

> Error creating repository: Forbidden (HTTP 403)
> You need admin access to the organization before adding a repository to it.

I have confirmed that I can create repos via the browser and I have two factor authentication.

**Comment by mislav** [comment]
Thank you for reporting! This might be related to the fact that perhaps we need to specify a team explicitly when creating the org repo #431, but I'm not sure

I'm mostly thinking that this is an API bug since you are able to create the repo in web, but not via API.

Are you using github.com or GitHub Enterprise? If the latter, which version? Thank you

**Comment by karthikskumar** [comment]
We're using github.com. Is there a flag I can use with a team name? I can try doing that.

**Comment by mislav** [comment]
There isn't a flag for team name in `hub create` yet, but you can try creating a repo over `hub api`:

```sh
hub api orgs/MYORG/repos -f name=MYREPO -F private=true -F team_id=TEAM-ID
```

Fill in your values (note that you'll have to use the numeric ID of a team rather than team name) and let us know if it works.

If it still fails, go to https://github.com/settings/tokens, find the "hub" token and check if you need to do “Enable SSO” for that token to be able to access your org (depending on the org access restrictions).

**Comment by karthikskumar** [comment]
I have SSO enabled; I tried the hub api and I was able to create the repo successfully. Does that confirm it's an API issue?

**Comment by mislav** [comment]
@karthikskumar Thanks for trying!

Does the `hub api` approach work even if you omit the `team_id` field completely?

**Comment by karthikskumar** [comment]
It does.

**Comment by mislav** [comment]
> It does.

Thanks for checking. But if you try doing it over `hub create` again, it still fails with a 403? That puzzles me because `hub create` is basically doing the exact equivalent of `hub api orgs/MYORG/repos -f name=MYREPO` (no team ID is passed).

**Comment by karthikskumar** [comment]
That is weird but it seems so.
![Screen Shot 2020-01-15 at 3 23 24 PM](https://user-images.githubusercontent.com/5762968/72480083-2224e500-37ab-11ea-9b5d-fa36af363285.png)

**Comment by karthikskumar** [comment]
However, if the repo exists in github, `hub create` detects existing repository and updates origin.

**Comment by mislav** [comment]
Thank you for the detailed info! Wow, that is so weird! You can [see here](https://github.com/github/hub/blob/b7b4a3df1de5ec4a21de769bdb77d57c32b53523/github/client.go#L225-L240) that the `hub create` operation is basically POSTing these fields to `org/MYORG/repos`:
- `name`
- `description`
- `homepage`
- `private`

It should be equivalent to `hub api orgs/MYORG/repos -f name=MYREPO`, since `hub api` and `hub create` use the same authentication mechanism. Can you maybe try supplying the `description` and `homepage` fields too, even if they're blank, in order to try to reproduce the 403 error? You can set `HUB_VERBOSE=1` in your environment to enable verbose debugging of HTTP operations; maybe you can spot what's different in these repo creation mechanisms.

Thanks for helping me debug this! I cannot reproduce this, so I'm guessing this might be org-specific.

**Comment by mislav** [comment]
@karthikskumar Friendly ping! Did you find anything new out using `HUB_VERBOSE`?

**Comment by sravikiran-CLGX** [comment]
I tried hub api as well as hub create. Both returned the prompt back without any error, however it did not create a Repo when I saw in UI. Anything that Am missing?

**Comment by sravikiran-CLGX** [comment]
@mislav @karthikskumar - Any thoughts on my above comment?

**Comment by mislav** [comment]
@sravikiran-CLGX No, sorry, that's someting to contact support@github.com about.

**Comment by karthikskumar** [comment]
@mislav Apologies for delayed response, a lot's been going on the last few months. :)
More importantly. I think I've identified the issue. This is silly but when looking back at the issue I realized that when I was using the hub api, I set `private=true` but while using the hub command I didn't use the private flag `-p`.

Using the private flag solves this issue.

**Comment by karthikskumar** [comment]
@mislav, Just a friendly FYI. Closing this issue.
