### ISSUE TITLE
`hub pull-request ` returns (HTTP 200) error on Github Enterprise

### ISSUE THREAD

**Issue by blind-gh0st** [github/hub#2439]
I am trying to create a pull request on a Github Enterprise server and I am getting the error:

`Error creating pull request: json: cannot unmarshal array into Go value of type github.errorInfoSimple (HTTP 200)`

I tried using the command:

`GITHUB_HOST=myenterprise.github hub pull-request`

I have a personal access token configured in `~/.config/hub`, I have tried both HTTP/S and SSH, and I have tried running `git config --global --add hub.host myenterprise.github`. I'm unsure as to what is going on here.

From what I researched that seems like a Go error, not necessarily a hub error.

Running Github Enterprise version 2.18.2

**Comment by mislav** [comment]
Hi, thank you for reporting and sorry to hear you're having trouble.

First of all, what is your `hub version`?

Second, can you try with `HUB_VERBOSE=1 hub pull-request` and see if the server response is shown in verbose output? If so, can you share with us the response? (Feel free to redact any private values such as repository names)

**Comment by blind-gh0st** [comment]
```
$ hub version
git version 2.24.1
hub version 2.13.0
```
[This is the output. It's very long and I redacted the important information.](https://gist.github.com/blind-gh0st/e45e146fdd8d8a5d12fe207790b0e22f)

**Comment by mislav** [comment]
Thank you! That helped me spot the issue: the POST to `https://[REDACTED-GITHUB-SERVER]/api/v3/repos/[REDACTED]/[REDACTED]/pulls` is responded to by the server with HTTP 301 redirect, and hub follows that redirect by doing a GET to `https://[REDACTED-GITHUB-SERVER]/api/v3/repos/[REDACTED]/[REDACTED]/pulls`, which is most definitely wrong since it needs to stay a POST.

```
> POST https://[REDACTED-GITHUB-SERVER]/api/v3/repos/[REDACTED]/[REDACTED]/pulls
> Authorization: token [REDACTED]
> Accept: application/vnd.github.shadow-cat-preview+json;charset=utf-8
{"base":"dev","body":"[REDACTED]","head":"[REDACTED]:[REDACTED BRANCH]","maintainer_can_modify":true,"title":"[REDACTED]"}
< HTTP 301
< Location: https://[REDACTED-GITHUB-SERVER]/api/v3/repos/[REDACTED]/[REDACTED]/pulls
> GET https://[REDACTED-GITHUB-SERVER]/api/v3/repos/[REDACTED]/[REDACTED]/pulls
```

Since it's a redirect, I'm guessing that the host names are different? I can't see that since they are both "REDACTED-GITHUB-SERVER".  Did your Enterprise instance change host names? If so, until hub fixes this, you can try working around this by opening your `.git/config` and changing the remote URL to have the new hostname.

**Comment by mislav** [comment]
HTTP redirect behavior is handled for us by Go, and it doesn't look like it supports following the 301 redirect for a POST with anything other than a GET: https://github.com/golang/go/blob/14b79df428fdab83ebc813a72ab714d1e2c488d2/src/net/http/client.go#L423-L433

Is it an option that your Enterprise admin makes it so that the redirect is performed with HTTP 308 instead of a 301? That should work with all other user agents, such as web browsers, but it would help hub follow the redirect correctly as well. HTTP 308 would be preferred here.

**Comment by blind-gh0st** [comment]
I didn't realize there was a redirect going on while I was using this. Talked to IT and I got a direct URL to use to hit the enterprise server and everything worked as expected.

I realize this is a Go thing, but it would be nice if we could catch that error and either explain that you can't do a redirect or to just try again with the redirected URL. Is that possible?
