### ISSUE TITLE
Add support for U2F security keys

### ISSUE THREAD

**Issue by erbesharat** [github/hub#2473]
**The problem I'm trying to solve:**
I only use my Titan security key for 2FA authentication and the CLI tool doesn't support the U2F security keys for login and only accepts the code from an authenticator app or SMS.

**How I imagine hub could expose this functionality:**
Doesn't need a separate subcommand, only use the default 2FA method from the user's account (SMS, App or security key). Also providing a flag like `hub issue -u2f` might be a good option too for forcing security key for commands.

There was a discussion about adding this feature in #1621 but that issue has been closed since a long time ago. Currently, I think it's possible to add this feature using a library like: `github.com/marshallbrekka/go-u2fhost`

P.S: I can take care of this one and create a PR if maintainers think it's necessary too.

**Comment by mislav** [comment]
Hi, we will not add any new features to the way hub currently does authorizations because the corresponding [Authorizations API is going away](https://developer.github.com/v3/oauth_authorizations/).

In future versions of hub, all authorizations will be going through an OAuth web flow where you will be able to use the U2F device of your choice.
