### ISSUE TITLE
hub alias for fish shell is wrong. twice.

### ISSUE THREAD

**Issue by KangOl** [github/hub#248]
For fish shell, the output of `hub alias` and `hub alias -s` are both wrong.
The output for `hub alias fish` must be
`eval (hub alias -s)`

And the output for `hub alias -s fish` must be
`alias git hub`
(I know the doc of alias say it support the current output, it doesn't work)

**Comment by corysimmons** [comment]
Care to update README with this?

**Comment by mislav** [comment]
@corysimmons The up-to-date information is already given to you when you run `hub alias` or `hub alias fish`. Perhaps README should instruct you to run `hub alias` to obtain the instructions for your current shell, rather than giving instructions for just bash/zsh? Care to submit this change as a PR?

**Comment by corysimmons** [comment]
Went to add it and there it was. lol, my bad. =)
