### ISSUE TITLE
Make signed-off-by stripping on PR configurable

### ISSUE THREAD

**Issue by robbat2** [github/hub#2486]
**The problem I'm trying to solve:**
PR#1752 made `hub` strip out the `Signed-Off-By` message trailer.

This is problematic if you are submitting to a project that:
- has policies requiring EVERY commit (including merges) to have a signed-off-by trailer
- uses the Merge button for accepting PRs

My workaround presently either invokes an editor or mangles messages for input, when I the behavior is already close at hand.

This behavior of `hub` ALSO differs from the GitHub/GHE web interface. Creating a new pull-request via the web interface for a single-commit PR includes the signed-off-by footer already.

**How I imagine hub could expose this functionality:**
 `hub pull-request -r -s ...`

Git already provides `-s/--signoff` to explicitly include a signoff. It should be available via command line option, as well as default in a configuration file.

**Comment by mislav** [comment]
Thanks for writing in!

`Signed-off-by` lines do not belong in a pull request body. They are not designed for pull request bodies, and they should not be required for pull request body. People will also most likely not write these lines manually into pull request body if they author a pull request via the web interface (i.e., not through hub).

Therefore, if a project has a policy that even merge commits should have `Signed-off-by`, the maintainers have two options:
1. They can add `Signed-off-by` manually in the textarea for the merge commit message when using the Merge button;
2. They can create merge commits manually in their local git repo and push them.

I don't think hub should do this, though, because it's overly project-specific.

**Comment by robbat2** [comment]
`should not be required for a pull request body`: This should be a project-specific decision, and should make it easier to reflect that decision.

All i'm asking is for an option for Hub to NOT remove the line if it's present. I'll write a PR for it.
