### ISSUE TITLE
Text does not appear and icon is different. (Visual Studio Code)

### ISSUE THREAD

**Issue by BlissfulBlue** [github/hub#2501]
![Capture](https://user-images.githubusercontent.com/62179850/76717421-b0fda180-6709-11ea-8f2f-1e6d956c65e9.PNG)

I'm a teenager and I have been recently learning how to code. However the problem is that every time I run the code, it comes up blank. Also, the 1: Code should say CMD (for command prompt), but it switches the letter to code. The icon for the file is also different. Originally, it looked like a piece of paper with C++ inside. Now, it looks like the VSC logo.
I've tried uninstalling and reinstalling.
I've tried going into properties and selecting different apps to open the code. (Like notepad or Visual Studio 2019).
I've tried searching the .JSON file (which I have no idea what to do there but I was told to go there).

I'm only 16 so I don't know what I'm doing. Can someone help?

**Comment by mislav** [comment]
Hi @BlissfulBlue, congratulations on learning how to code!

I'm afraid that this is the wrong place to ask questions about VS Code or writing C++ programs. This is an issue tracker for a [project called "hub"](https://github.com/github/hub#readme) that's written in Go and is entirely unrelated to any of the problems you are asking about.

I haven't coded in C++ so I'm not going to try give you any guidance, but the thing I notice that you're doing wrong is that you're trying to execute the code in the `Undo.cpp` file by typing out the name of that file in the terminal. That will not work. You need to first compile that file into an exe (which I notice you did because there is a `Undo.exe` file) and then run it in the terminal like so: `.\Undo.exe`.

[These resources](https://code.visualstudio.com/docs/cpp/config-msvc) might be a good starting point for you, and when you get stuck, you can try asking on Stack Overflow.

Good luck!
