### ISSUE TITLE
hub create asks for username and password when it should be using ssh

### ISSUE THREAD

**Issue by DAMO238** [github/hub#2522]
**Command attempted:**
`hub create` with `git config --global hub.protocol ssh`

**What happened:**
Every time you run this, rather than asking for my ssh key password, like git would when running git push, it asks for my username and password (which won't work because I don't have any access tokens set up for repository creation and my main password needs 2fa)

**More info:**

Hub version: 2.14.2
Git version: 2.26.1
OS: Arch (kernel: 5.6.4-arch1-1)
`git remote get-url origin` output is `git@github.com:DAMO238/dotfiles.git`

**Comment by mislav** [comment]
Hub needs to communicate with the GitHub API, and that communication cannot be done over SSH https://github.com/github/hub/issues/1644#issuecomment-359002547. Therefore, hub needs to authenticate with your username + password + 2FA. If you had actually given your real password, you would be prompted for 2FA (trust me— it will work!). You may also generate a token and paste that instead of your real password.

The SSH protocol is used only for git operations like clone, fetch, and push, but API communication is done separately from git and that's why we sometimes need two separate modes of authentication.
