### ISSUE TITLE
Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by PaulRBerg** [github/hub#2548]
**Command attempted:**

`hub clone author/reponame`

**What happened:**

The command executed as expected, but I later received this email from GitHub:

> On May 18th, 2020 at 17:01 (UTC) your personal access token (hub) using yarn/1.22.4 npm/? node/v12.16.3 darwin x64 was used as part of a query parameter to access an endpoint through the GitHub API.
>
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.

I'm sure that my "hub" token is used by the hub command-line tool. I suppose the solution is for hub to start using the latest authentication mechanism?

**More info:**

+ git version 2.24.1
+ hub version 2.14.2
+ macOS 10.15.4

**Comment by mislav** [comment]
Hi, this deprecation notice is about your hub token being used by a tool other than hub. I can tell this because hub never passes the token via `access_token` query parameter.

The tool using this token seems to be yarn. I don't know how you've set up yarn to authenticate with GitHub, but you might look into generating a token specifically for yarn and upgrading yarn to a version that doesn't trigger this notice.

**Comment by PaulRBerg** [comment]
Oh, I see. Thanks for your help!
