### ISSUE TITLE
github.com username: github.com password for  (never stored): Requires authentication

### ISSUE THREAD

**Issue by iiinsomnia** [github/hub#2571]
**Command attempted:**

```sh
git tag | xargs hub release delete
```

**What happened:**

```sh
github.com username: github.com password for  (never stored): Requires authentication
```

**More info:**

```sh
[env] macOS Catalina 10.15.3
[git version] 2.26.2
[hub version] 2.14.2 
```

**Comment by benknoble** [comment]
Well, I don't know how to fix it (maybe use the environment variables for user/pass?), but this happens because hub reads those values from standard in, which has been taken over by the pipeline--nothing to read, or at least not the right things.

**Comment by mislav** [comment]
@iiinsomnia I'm sorry for the bad experience! The explanation by @benknoble is accurate; hub was not authenticated yet and wasn't able to prompt because stdin wasn't connected to a terminal.

As a workaround, first run `hub release` to authenticate hub and then you can run any other hub commands. Alternatively, you may supply an authentication token via the GITHUB_TOKEN environment variable.
