### ISSUE TITLE
comment on issue

### ISSUE THREAD

**Issue by sellout** [github/hub#623]
We have a few scripts that automate a lot of our workflow, and currently it uses `hub` a bit. One thing I want to be able to do is automatically add a comment to an issue like “This issue is being worked starting from sellout/slamdata@123764327412736.” when the first push to the branch named “wip/264-some-issue” happens.

**Comment by mislav** [comment]
After some consideration, I have decided that—for now—this is best implemented in user scripts, rather than maintained in hub core. Now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3 https://github.com/github/hub/pull/2016

For example:
```sh
hub api repos/{owner}/{repo}/issues/1234/comments -f body='This is my comment!'
```

Thank you for suggesting!

**Comment by JLLeitschuh** [comment]
@mislav is there some kind of good way for `hub api` to autofill the `{owner}`, `{repo}` and `{pr_number}` from the contextual information that hub captures.
