### ISSUE TITLE
Don't store OAuth token in ~/.config

### ISSUE THREAD

**Issue by glittershark** [github/hub#630]
Like most developer UNIX users, I like to keep configuration files in a 'dotfiles' repo. Because of things like GTK config, I include the `~/.config` folder in that repo, as I'm sure many people do as well. However, since `hub` stores the oauth token in `~/.config/hub` I have to add an explicit entry to my `.gitignore` to prevent that file from getting committed to my public `dotfiles` repo. That's all fine, except I'm sure there are some less-vigilant users out there who have run `git add .config` and unwittingly granted full access to their github account to the world. It seems to me like `hub` should make this sort of silliness less easy to do accidentally.

**Comment by technomancy** [comment]
I believe `git` is already capable of reading credentials out of `~/.netrc.gpg` using `git-credential-netrc`, which would make a lot more sense than storing extremely sensitive credential data in plaintext. Would it be possible to make `hub` use whatever credential helper `git` is already configured to use?

**Comment by mislav** [comment]
@technomancy Yes I'm interested in adding a feature to hub to support a credential helper. Any advice about the exact protocol used for talking to a credential helper would be welcome.

**Comment by technomancy** [comment]
As a temporary workaround, I'm using this wrapper around `hub`:

```bash
#!/bin/bash

HUB_CONFIG_GPG=$HOME/.config/hub.toml.gpg
export HUB_CONFIG=$(mktemp -t tmp.XXXXXXXX.hub)

function finish {
  rm -rf "$HUB_CONFIG"
}

trap finish EXIT

gpg -q -d "${HUB_CONFIG_GPG}" > "${HUB_CONFIG}"

exec "${HOME}/src/hub/bin/hub" $@
```

**Comment by technomancy** [comment]
@mislav Thanks; I will do some digging and see if there's a way for non-`git` programs to tap into the methods it uses for resolving credentials. Too bad this isn't done in Ruby any more, since I already implemented support for this there. =)

**Comment by elyscape** [comment]
@mislav [See here][git-credential]. Basically, you run `git credential` with an argument of either `fill`, `approve`, or `reject`:

- `fill` retrieves credentials
- `approve` stores credentials
- `reject` removes stored credentials

Then, on stdin, you feed it something in [this format][format], followed by an empty line. The format is basically `key=value`, with the following keys:

- `protocol` is the protocol (e.g. `https`, `ssh`, `git`)
- `host` is the remote hostname (e.g. `github.com`)
- `path` is the path to the remote repository (e.g. `github/hub.git`)
- `username` is the username (e.g. `mislav`)
- `password` is the password (or, in our case, the personal OAuth token)
- `url` is the full clone URL

Which of these must be provided will depend on what command you're using. For `fill` and `reject`, you only need to specify `protocol` and `host`, though `path` and `username` may optionally be provided if available. For `approve`, `protocol`, `host`, `username`, and `password` should be provided, though `path` can also be provided if you want to provide credentials specific to a particular repository. If you provide a value for `url`, any other values that are present in it will be parsed out (e.g. `https://elyscape:oauth-token@github.com/github/hub.git` has values for `protocol`, `host`, `path`, `username`, and `password`).

If you're performing a `fill` operation, the command will then spit out something like this:
```
protocol=https
host=github.com
username=elyscape
password=oauth-token
```

You can also call the credential helpers directly. [They work the same as `git credential`][api-credentials], except that their commands are `get`, `store`, and `erase` instead of `fill`, `approve`, and `reject`. Still, it's probably better to use `git credential` and let it worry about paths and which helper to use.

[git-credential]: https://git-scm.com/docs/git-credential
[format]: https://git-scm.com/docs/git-credential#IOFMT
[api-credentials]: https://github.com/git/htmldocs/blob/gh-pages/technical/api-credentials.txt#L177

**Comment by elyscape** [comment]
As a side note, calls to `git credential` will, by default, [filter out the repo path if the protocol is HTTP(S)][useHttpPath] before passing the parameters to the credential helper.

[useHttpPath]: https://git-scm.com/docs/gitcredentials#gitcredentials-useHttpPath

**Comment by mislav** [comment]
Thanks for the research. That seems reasonable. The tricky part of implementing this is going to be deciding what to do with existing credentials that might be stored for `https://github.com/`, but which are a Personal Access Token that someone generated for git cloning purposes only and which wouldn't work with a bunch of operations that hub needs to utilize the API for.
