### ISSUE TITLE
Completion for Fish-Shell

### ISSUE THREAD

**Issue by natrim** [github/hub#656]
Hello,

it would be nice to have autocompletion for fish-shell.

**Comment by hasit** [comment]
Hello. I've been using fish shell for over a year now I am interested in implementing this feature for Hub. As @narqo said, the problem lies in the fact that Hub's man pages does not list all it's options (assuming that it is aliased as git).
I know it a longer route, but would reformatting the Hub man pages help?

**Comment by mislav** [comment]
@hasit Yes, we need to improve our man pages (e.g. break the big man page that we have into individual ones), and it would be great if the same pages could be used by fish to extract autocomplete information.

**Comment by lukaszlenart** [comment]
Started working on some initial script
https://github.com/lukaszlenart/hub-fish-completion
