### ISSUE TITLE
build failure on ubuntu 14.4

### ISSUE THREAD

**Issue by koo5** [github/hub#710]
```
 ./script/build 
# github.com/github/hub/github
/tmp/go/src/github.com/github/hub/github/http.go:131: unknown net.Dialer field 'KeepAlive' in struct literal
/tmp/go/src/github.com/github/hub/github/http.go:133: unknown http.Transport field 'TLSHandshakeTimeout' in struct literal
```

what do?

**Comment by spearsem** [comment]
This is a very annoying dependency. I don't want to go out of my way installing go from source just to be able to use hub. Especially since I [won't be using go for any meaningful projects myself](http://crufter.com/2014/12/01/everyday-hassles-in-go/). I'd like to keep go off my machine. This is a good reason to just ignore hub.

As far as I'm concerned, this kind of dependency should be considered a bug worth fixing.

**Comment by jingweno** [comment]
@spearsem You don't need a Go compiler to use `hub`. You could just [download a pre-built binary](https://github.com/github/hub/releases/tag/v2.2.0-rc1) for your platform. This is [documented on the README](https://github.com/github/hub#standalone). You only need a Go compiler if you develop `hub`.

Thanks for sharing a post ranting about Go. You actually can find most answers [here](http://golang.org/doc/faq), e.g., Why does Go not have generic types etc.. I personally think [Go is the best solution for `hub`](http://owenou.com/2013/12/22/fast-github-command-line-client-written-in-go.html).

**Comment by spearsem** [comment]
If I want to build hub from source (which is a reasonable thing to want, even if there are binaries) then I have to also build go from source (because, for even Ubuntu 14.04 LTS, the current package repo version of go is not new enough to meet the dependencies for hub).

I'm not ranting against go: many people like it or even just enjoy it and I encourage them to continue using it to their heart's content. I'm just saying there are pretty valid reasons why a person might want to have as little to do with go as possible, and for them (if they don't just want a hub binary -- which again is quite a reasonable thing) it seems they are better off ignoring hub.

**Comment by jingweno** [comment]
@spearsem I think I have to correct you on the installation of Go. As I said, you seldom need to build Go from source. If you can't install Go from a dependency manager like `apt-get` or `brew`, the best way is to [download Go](https://golang.org/dl/) for your platform and put it in the `PATH`. We have been doing that in our [Vagrant VM](https://github.com/github/hub/blob/master/Vagrantfile) for compiling pre-built binaries. Here's [the script](https://github.com/github/hub/blob/master/Vagrantfile#L40-L43) if you want to take a look. That being said, I think we could write something down on the README to be more friendly to people who want to build `hub` from source.

**Comment by spearsem** [comment]
I am reading [Go's install page](https://golang.org/doc/install) and after reading it, then googling each of the following questions, I still am not clear about their answers:

1. Is go 1.4 supported for Debian? (Install page suggests not; I can find web pages outlining homemade packages, but not clear if I can get a version new enough for hub). If I was a Debian user, I would already stop right there -- already too much time wasted to see how I can even install this thing.

2. Is go 1.4 supported for CentOS or Red Hat? (Install page suggests not; again I can find web pages seeming to show random workarounds and personal packages). Is this going to be significantly different for 32-bit v. 64-bit.

I happen to use Ubuntu, but I also either currently use or have used a mix of OS X 10.95. Debian, CentOS, and Red Hat on my work machines, or on communal work servers where I have a small amount of freedom to install software.

If I work from home and I want my working environment to be the same (crucially, to make the setup instructions as similar as possible across all platforms, to reduce the number of idiosyncratic scripts needed for installing on one platform vs. another) this is a problem. 

I guess what frustrates me is that you seem to want to push me to the binary download page -- as if the exist of pre-built binaries magically solves this problem. It doesn't. That's not a good answer. If someone wants to build hub from source and runs into platform issues or go issues, it's not a reasonable answer to say "stop wanting that and just use this binary, which may or may not be available for some/all of the platforms you work on." 

And for something that needs to "just work" at every terminal prompt that I fire up (like git, and by extension hub) this is even more egregious and even less appropriately fixed with "just get the binary."

**Comment by jingweno** [comment]
> I guess what frustrates me is that you seem to want to push me to the binary download page -- as if the existence of pre-built binaries magically solves this problem. It doesn't.

I'm not pushing you to anything...I'm suggesting using a pre-built binary is usually the easiest way to run an application. When you choose to build from source, you're making a tradeoff and you need make sure all dependencies are met (never an enjoyable experience). The [Go Linux compiler on download page](https://golang.org/dl/) works for most if not all Linux system, including Ubuntu, CentOS and Debian. So are the `hub` binaries that [we provided for release](https://github.com/github/hub/releases/tag/v2.2.0-rc1).

>  If someone wants to build hub from source and runs into platform issues or go issues, it's not a reasonable answer to say "stop wanting that and just use this binary, which may or may not be available for some/all of the platforms you work on."

Apparently this is not our goal. @mislav and I deeply care about this project and we're working hard to make sure `hub` is available on all common platforms. If you find anything not working, please do file us a bug report.

**Comment by mislav** [comment]
> If you are on an OS for which the Go binaries are not available, and you also want to build hub from source then you must try to build Go from source.

That is true, and there will be no way around this. Unless someone rewrites hub in C or Java, the bar for development on different platforms will always be how to install the compiler/interpreter. The same obstacle was when hub was written in Ruby— you needed the Ruby interpreter, which might not be readily available precompiled for all platforms.

I don't feel that this discussion is leading anywhere productive. We picked Go to implement hub for now for good reasons. For some people it might be tricky to contribute to or compile hub from source. It shouldn't be impossible, though. We're fine with this situation for now.
