### ISSUE TITLE
hub pull-request fails when repo name has changed.

### ISSUE THREAD

**Issue by aeslaughter** [github/hub#777]
I work on a project that has a number of forks, but it is common for the forks to be renamed. Github still show the renamed repository as forked; however, hub pull-request does not create the pull request. The commands work fine for the case when the fork has not been renamed.

**Comment by mislav** [comment]
What does it mean "hub pull-request does not create the pull request"? What is the exact things that happens, and why do you think it's because of renamed repositories? What are the git remotes in your local repo? Which is the base of the pull request (typically the "master" branch in "origin" remote) and where is the head of the pull request (typically a topic branch on your fork)

**Comment by aeslaughter** [comment]
Correct, hub pull-request does not create the request. I think it is the renamed repositories because I have a script that is running the command and the request *is* created when the name is the same.

I will double check the behavior and report back.

**Comment by aeslaughter** [comment]
So here is the situation:
[`permcody/inch_worm`](https://github.com/permcody/inch_worm) *is* a fork of `idaholab/stork`. If I do the following query, permcody/inch_worm is in the list returned.
```
curl -i https://api.github.com/repos/idaholab/stork/forks?per_page=1000 | grep permcody
```

```
...
"html_url": "https://github.com/permcody/inch_worm",
...
```

Running this
```
hub pull-request -h hub-test -b permcody:master -m "hub PR Test"
```

causes this
```
Error creating pull request: Not Found (HTTP 404)
Not Found
Are you sure that github.com/permcody/stork exists?
```

The answer is of course NO, b/c the PR should go to `permcody/inch_work`.

**Comment by mislav** [comment]
Ah I see. You're specifying the base of the pull request explicitly, and the current repo's `origin` points to the canonical `idaholab/stork` repo right?

Because you're specifying the base branch explicitly, and your fork's name doesn't match the canonical repo's name, you must also specify the name of your fork:

```
hub pull-request -b permcody/inch-worm:master ...
```

**Comment by aeslaughter** [comment]
That is all I needed to know I guess, my mistake for not understanding the syntax. Thanks.
