### ISSUE TITLE
Does not support syntaxes like `hub init -g DIRECTORY`

### ISSUE THREAD

**Issue by Arnie97** [github/hub#790]
Git itself supports syntax like `git init DIRECTORY`, which initializes the repo in the specified directory (possibly after creating it).
But as for hub, `hub init -g` always takes cwd as the path of newly initialized repo. So, in cases like `hub init -g DIRECTORY`, the hub command, which is supposed to function in the specified directory, still stays in the current working directory, and is likely to raise an error like this:
```fatal: Not a git repository (or any of the parent directories): .git```

**Comment by mislav** [comment]
Good catch! Thanks for reporting

**Comment by jingweno** [comment]
@Arnie97 Great find! I've attempted a fix in https://github.com/github/hub/pull/791. What version of `hub` you're running? The Ruby Hub (1.x) [has similar issue](https://github.com/github/hub/blob/1.12-stable/lib/hub/commands.rb#L552). The fix is on the Go Hub so you will see the fixes in the next 2.2.0 release. You could also try out `brew install --HEAD hub` if you can't wait :wink:

**Comment by Arnie97** [comment]
@jingweno I'm quite new to hub, so I'm using hub 2.2.0-rc1. As a matter of fact, I was not aware of hub until a glance through the [template boxen by github](https://github.com/boxen/our-boxen) last week.
