### ISSUE TITLE
Using hub with SSO GH:E instances

### ISSUE THREAD

**Issue by paulcbetts** [github/hub#826]
How do you set up hub with a GH:E instance that uses SSO? Generating an OAuth token and using it as my password fails with the error:

```
paul@psamathe% git issue
my-ghe-instance.com username: paulcbetts
my-ghe-instance.com password for paulcbetts (never stored): 
Error getting issues: Forbidden (HTTP 403)
This API can only be accessed with username and password Basic Auth
```

This appears to be by-design, but I don't know what else I could be putting for the password field

**Comment by mislav** [comment]
Since it doesn't seem we can support SSO flow from the command line, there's currently no way to authenticate with these GH:E from hub. You must generate a Personal Access Token and put it manually in `~/.config/hub`:

```yaml
---
myenterprise.com:
- protocol: https
  user: mislav
  oauth_token: PERSONALTOKEN
```

In the next release we need to make it possible for you to just paste the Personal Access Token as password and have that stored in the config file. Follow #384 for updates.

**Comment by paulcbetts** [comment]
:cool::+1:
