### ISSUE TITLE
Have to reenter credentials on Windows

### ISSUE THREAD

**Issue by twsouthwick** [github/hub#837]
I cloned a repo on Win10 64-bit and it worked fine.  However, when I tried removing a remote branch (git push origin :[branch name]) it asked me for my credentials again.

My version:
git version 1.9.5.msysgit.0
hub version 2.2.0

**Comment by Nicofuma** [comment]
I noticed the same thing and in my case it seems to be due to a '|' in the password: hub stop aking for my password as soon as I type the '|' character

**Comment by mislav** [comment]
We're having some trouble on Windows, although we're not sure why: #815

From what I can tell, the password prompt is definitely busted. However, @twsouthwick said that he managed to input the password and it worked, but it wasn't persisted. The next time that happens, can you check that the successful password prompt did persist the auth credentials in `$HOME/.config/hub`? (I'm not sure what is the user's home directory on Windows.)

Also, please try with latest hub version v2.2.1, thanks!

/cc @jingweno

**Comment by jingweno** [comment]
@Nicofuma I was able to type "|" on a 32 bit Windows with v2.2.1. Let me try on 64 bit as well. I'm using the Git shell comes with [GitHub Windows](https://windows.github.com/). What's your terminal?

We could try upgrading the [gopass](https://github.com/howeyc/gopass) lib and see if it fixes the issues. We're missing 2 latest Windows fixes.

**Comment by Nicofuma** [comment]
@jingweno I will update hub and try tonight to see if I can reproduce the issue.

**Comment by Nicofuma** [comment]
@jingweno I just reproduced it and actually it's not related to a specific char but to the password length: the prompt stop just after the 15th. So if your password has more than 15 chars you're stuck.

Reproduced with `git bash` and `powershell` (with powershell it even stops after the 13th)

**Comment by mislav** [comment]
I was able to reproduce the problem in Windows 8.1 Powershell with hub 2.2.1:

```
C:\Users\IEUser\Documents> .\hub clone playground
github.com username: mislav
github.com password for mislav (never stored):
←[36m> POST https://api.github.com/authorizations←[0m
←[36m> Authorization: Basic [REDACTED]←[0m
←[36m{"scopes":["repo"],"note":"hub for IE11Win8_1\\IEUser@IE11WIN8_1","note_url":"http://hub.github.com/"}
←[0m
←[36m< HTTP 401←[0m
←[36m{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}←[0m
Error cloning repository: Unauthorized (HTTP 401)
Bad credentials
```

My password is longer than 15 characters. I tried to paste it in using <kbd>Ctrl-V</kbd> but it failed with output above. Then I thought that maybe <kbd>Ctrl-V</kbd> is not supported by Powershell, and I choose "Edit > Paste" from Powershell menu. And that worked!

I counted 2 hub bugs, though:

1. The verbose output contains ANSI escape colors that aren't supported in Powershell. We should not output color on Windows.

2. When you `hub clone mislav/anyenv` (a public repo) on a pristine system, you get prompted for authentication information, but even if that fails, the repo will be cloned anyway because all the information to guess the GitHub clone URL is on the command-line and API information isn't strictly necessary. However, the successful clone might fool you into believing that your authentication info was accepted and stored. But if authentication failed in the first place, no auth info will be stored and you will get prompted for authentication info on next usage of hub, which is confusing to the user.

**Comment by jingweno** [comment]
I can reproduce it on a 64bit Windows 10 by typing a password more than 15 characters - 32bit Windows works okay though. 

@mislav 

> The verbose output contains ANSI escape colors that aren't supported in Powershell. We should not output color on Windows.

The ANSI escape colors is fixable on Windows. I have been through similar fixes with [go-colorable](https://github.com/mattn/go-colorable).

>  you get prompted for authentication information, but even if that fails, the repo will be cloned anyway because all the information to guess the GitHub clone URL is on the command-line and API information isn't strictly necessary

Yeah, this is pretty confusing. Will fix it as well.

**Comment by dobau** [comment]
I have the same problem when type the "0" of my password.

```bash
C:\Users\Rafael\workspace\vraptor4>hub pull-request -i 991 -b caelum/vraptor4 -h
 dobau/vraptor4 https://github.com/caelum/vraptor4/issues/991
github.com username: dobau
github.com password for dobau (never stored):
Error creating pull request: Unauthorized (HTTP 401)
Bad credentials
```

**Comment by jingweno** [comment]
@dobau This should be fixed in https://github.com/github/hub/pull/927. And we'll cut a release for 2.2.2 soon. At the meant time, do you mind [building the latest master](https://github.com/github/hub#source) and see if it fixes the issue?
