### ISSUE TITLE
Feature: Managing collaborators via `hub`

### ISSUE THREAD

**Issue by tejasmanohar** [github/hub#844]
IMO, a good feature would be adding a collaborator via `hub` commands. For example,

```
hub collab MY_USER/REPO add OTHER_USER
hub collab MY_USER/REPO remove OTHER_USER
```

What do you think? I'd be interested in PR'ing this but want to hear from other users of `hub` first.

**Comment by mislav** [comment]
Sorry for late reply. It might be a useful feature, but personally I wouldn't like to maintain it in the long run and I don't think it would see much use. Also, it would be vulnerable to typos: you might type `hub collab MYUSER/REPO add milsav` and think you added me but instead you added a person called "milsav" (a misspelling). In the web interface this is harder to do because we show you the person's full name and avatar so that you can double check whether that's the person you really wish to add.

Because of that, I don't think we'll be adding this feature.
