### ISSUE TITLE
Hub configures $EDITOR differently than git when creating PR

### ISSUE THREAD

**Issue by jasonkarns** [github/hub#845]
When vim is opened for creating a commit message, it is detected as a GITCOMMIT filetype. This configures vim to colorize the summary line (up to 50 chars IIRC). It also warns via color when there is text on the 'spacer' line between summary and description.

When vim is opened from hub for commit messages, it is also detected as a GITCOMMIT filetype. So I get all the same line-specific coloring and highlighting. However, when editing an actual commit message, it automatically softwraps at 80chars or so. When opened via hub, there is no softwrapping.

My confusion is why these are behaving differently. As mentioned, the filetypes are set correctly in both instances, so vim knows it's editing a GITCOMMIT filetype. Is git doing something differently when opening the editor that hub isn't?

**Comment by mislav** [comment]
Hub turns hardwrapping (not softwrapping) off for PR messages because every line break would be preserved in GitHub-flavored Markdown. That means if you author text hardwrapped at column 80, that wrapping will unfortunately get preserved in rendered Markdown on the opened pull request and look terrible. 709f1cf1ce9196890d0854cec84505b1bc5d1fe7

For git commit messages, they should be hardwrapped because we don't process them as Markdown in the web UI.

**Comment by jasonkarns** [comment]
Thanks for the clarification! I'll have to look into turning softwrapping
on its place.

**Comment by mislav** [comment]
As improbable as it sounds, I haven't been able to figure out how to turn on soft wrapping on a specific column (e.g. 80) so that lines appear wrapped, but there are no actual newline characters. I've only been able to turn on softwrapping at the edge of the screen (`:set wrap`). Because my terminal screen is fairly wide, I find this line length to be difficult to write and read with. :unamused:
