### ISSUE TITLE
unable to clone or go get

### ISSUE THREAD

**Issue by vtolstov** [github/hub#846]
```
# cd .; git clone https://github.com/github/hub /home/vtolstov/go/src/github.com/github/hub
Cloning into '/home/vtolstov/go/src/github.com/github/hub'...
error: object 9ef2af57366f63deb751b92a8ca630fe598b10f0:contains zero-padded file modes
fatal: Error in object
fatal: index-pack failed
package github.com/github/hub: exit status 128
```

**Comment by mislav** [comment]
Sorry that you're having trouble.

1. If you try again, does the same error pop up?
2. What's your version of git? If you update the version, does the same problem happen?
3. If you want to install hub, you might have better luck grabbing one of our pre-built binaries in the Releases section.

**Comment by vtolstov** [comment]
1) yes error persists
2) git 2.2.2
3) i need to clone repo. i think that github breaks this repo =(

**Comment by mislav** [comment]
I just did a health check on `github/hub` repo and there were no issues. Also, I can't reproduce with git 2.1.4. I might try upgrading git, but in the meantime, can you rule out network issues by retrying the operation from another network, or if you have a HTTPS proxy bypassing the proxy?

**Comment by mislav** [comment]
Also, trying with git 2.3 for good measure would be a good idea as well. Sorry I can't help you better :(

**Comment by vtolstov** [comment]
under git 2.3.3 nothing changed.
try run git fsck for cloned repo.

**Comment by mislav** [comment]
Hmm yes I get the same error when I run `git fsck`. I think this might be a problem with strict fsck settings on your computer. Try this:

```
git -c fetch.fsckObjects=false clone ...
```

There is nothing we can do about these objects in the hub repo, as they're immutable and permanent part of the project's history. However, once you've initially cloned with fsck disabled, it should be safe to re-enable fsck to your original setting and do fetches on the same repo, because no new object should be corrupted.

**Comment by vtolstov** [comment]
Thanks, this solves my issue. But i think this info may be suitable for readme, because i'm not only one who enable fsck in git.

**Comment by fowlslegs** [comment]
I second including this in the README.
