### ISSUE TITLE
Add option to browse to view a pull request

### ISSUE THREAD

**Issue by ElDeveloper** [github/hub#849]
In the context of working on a PR, it is nice to be able to go to the web app and comment, discuss, etc. That's why I think it would be nice if something like `hub browse pull-request`, so that it checked if you are working on a branch that's been submitted to the upstream (or another remote) as a PR and opened a browser window so you can continue the conversation.

**Comment by mislav** [comment]
Thanks for the suggestion! It's planned. In the meantime you can use this shell script:

```sh
#!/bin/bash
# Usage: git open-pr [<branch-name>]
#
# Navigates to the pull request for a branch using the web browser.
# Defaults to current branch.
set -e

branch="${1:-$(git symbolic-ref HEAD)}"
branch="${branch#refs/heads/}"

remote_url() {
  git remote -v | grep "^$1" | head -1 | grep -o 'github.com[/:]\S\+'
}

url="$(remote_url upstream || true)"
url="${url:-$(remote_url github || true)}"
url="${url:-$(remote_url origin || true)}"
url="${url%.git}"

open "https://${url/:/\/}/pull/${branch//\//%2F}"
```

**Comment by ElDeveloper** [comment]
It's awesome to hear this will be implemented in the future, thanks for
the workaround, this is exactly what I was looking for!

**Comment by OliverJAsh** [comment]
:+1:

**Comment by bcjordan** [comment]
@mislav in my case, in bash, I had to change the

```
https://${url/:/\/}/pull
```

to

```
https://${url/://}/pull
```

with no \. Otherwise it pointed to `https://github.com\/username/reponame/pull/branchname`








p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px Inconsolata; color: #eeeeee; background-color: #000000}
span.s1 {font-variant-ligatures: no-common-ligatures}



https://github.com\/code-dot-org/code-dot-org/pull/details_polyfill













p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px Inconsolata; color: #eeeeee; background-color: #000000}
span.s1 {font-variant-ligatures: no-common-ligatures}



https://github.com\/code-dot-org/code-dot-org/pull/details_polyfill













p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px Inconsolata; color: #eeeeee; background-color: #000000}
span.s1 {font-variant-ligatures: no-common-ligatures}



https://github.com\/code-dot-org/code-dot-org/pull/details_polyfill

**Comment by mislav** [comment]
@bcjordan Thanks! Corrected
