### ISSUE TITLE
Print which pull request(s) a commit is part of

### ISSUE THREAD

**Issue by glittershark** [github/hub#854]
I had the idea today of adding a list similar to Github's commit view of which pull requests my HEAD is part of to my prompt. Initially the idea would be knowing whether or not I'd already submitted a pull-request for my current branch, but there are lots of other cool applications when log-spelunking. Maybe even an extension to `git show` that adds PR lists in addition to the existing information?

**Comment by glittershark** [comment]
More thoughts: `git branch --contains` exists. Why not `git pull-request --contains`?

**Comment by mislav** [comment]
Sure, good idea! We're still compiling what we want as a feature set for the next major release (lots of pull-request and issues-related ideas).

**Comment by mislav** [comment]
After some consideration, I have decided that—for now—this is best implemented in user scripts, rather than maintained in hub core. Now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3 https://github.com/github/hub/pull/2016

Thank you for suggesting!

**Comment by fgrehm** [comment]
Here's how I'm doing this in case anyone else is interested: https://github.com/fgrehm/find-pr-for-commit/blob/master/find-pr-for-commit
