### ISSUE TITLE
Gemfile still needed?

### ISSUE THREAD

**Issue by tfarina** [github/hub#884]
Is it still needed?

**Comment by mislav** [comment]
Yes, Gemfile is still needed because our `features/` test suite runs using Cucumber which is implemented in Ruby.

There are Go tests that you can run using `script/build test` and those don't need any Ruby. But, our most comprehensive test suite is in `features/` and is still very important. That's why we're keeping Ruby as a development dependency.

Don't worry, if you can't run those tests locally, they will be run by Travis CI whenever you open a pull request.
