### ISSUE TITLE
hub fork shows `git remote add` usage

### ISSUE THREAD

**Issue by pwaller** [github/hub#892]
I just tried to run hub fork and instead got the `git remote add` usage. I'm sat in a clone of `https://github.com/robertkrimen/gphr/`, running `hub fork` (`hub pull-request` and others work fine). Strace shows that `git remote add -f https://github.com/robertkrimen/` is being run, which makes git remote show the usage.

~~The fork is not being created in my account.~~

~~I guess from the code that an error is being ignored somewhere, since [it reaches the git remote add](https://github.com/github/hub/blob/64187e3cb84c6956826acad2803958730a7ea180/commands/fork.go#L77) despite the fact that this is the last thing that happens and the fork has apparently failed.~~

Edit: Strange, looks like the fork is being created in my account. I couldn't find it before. Maybe I spoke too soon?

**Comment by HerbCSO** [comment]
You got further than I did in figuring out which command is being run that is causing this. I have the same problem and I'm also looking for a solution. 

Running on Yosemite 10.10.3, git version 2.4.5 and hub version 2.2.1 installed by Homebrew. 

It looks like the remote name is added in https://github.com/github/hub/blob/v2.2.1/commands/fork.go#L77, so I imagine something is happening with the arguments processing in https://github.com/github/hub/blob/v2.2.1/commands/commands.go#L117, but that is a total SWAG since I don't know Go at all, really, so I'm probably totally wrong there. ;]

**Comment by mislav** [comment]
Is it possible that any of you were using an old git version that didn't support `-f` flag for `git remote add`? Check your `git help remote` documentation.

This is the first idea that comes to my mind. Otherwise, `git remote add -f URL` is a valid command.

**Comment by pwaller** [comment]
@mislav I think you misread the command that I stated was being run. The word `add` is missing, so it's just calling `git remote -f URL`.

**Comment by pwaller** [comment]
However, whatever the failure it's now working for me on

```
git version 2.1.4
hub version 2.2.1
```

**Comment by mislav** [comment]
Thanks for the update!
