### ISSUE TITLE
Add ability to create issues

### ISSUE THREAD

**Issue by bcherny** [github/hub#893]
```
$ git issue -m "Add ability to create issues" -t enhancement -t feature-request
https://github.com/github/hub/issues/893
```

**Comment by patcon** [comment]
This is probably what you want: https://github.com/stephencelis/ghi

**Comment by bcherny** [comment]
@patcon that's pretty cool, but shouldn't issues be part of hub core?

**Comment by patcon** [comment]
well if you create issues, then you probably want a way to label/open/close/assign etc, and it quickly turns into something you might just want a special tool for :)

Meh. I find ghi suits me just fine

**Comment by bcherny** [comment]
the thing is, hub already supports some of those features for pull requests. it should at least support those same features for issues.

**Comment by patcon** [comment]
It actually doesn't do any of those things -- just creation of PRs, which happens to involve a deprecated feature to create them from issues :)

**Comment by bcherny** [comment]
Well it does support the opening part :) the ability to open issues (no labels or assignees) would be helpful.

**Comment by mislav** [comment]
This is on our roadmap but it's not our foremost priority right now. We're first going to improve the `browse`, `release`, and `pull-request` commands.

I'm closing because we're already tracking this feature and I need to clean up our issue tracker. Thanks for the suggestion!

**Comment by hryamzik** [comment]
#371 seems to be related

**Comment by mislav** [comment]
`hub issue create` functionality is now merged to master!

**Comment by fuchao2012** [comment]
@mislav `issue create ` is cool. Do we have a help list like below?

```
usage: ghi [--version] [-p|--paginate|--no-pager] [--help] <command> [<args>]
           [ -- [<user>/]<repo>]

The most commonly used ghi commands are:
   list        List your issues (or a repository's)
   show        Show an issue's details
   open        Open (or reopen) an issue
   close       Close an issue
   lock        Lock an issue's conversation, limiting it to collaborators
   unlock      Unlock an issue's conversation, opening it to all viewers
   edit        Modify an existing issue
   comment     Leave a comment on an issue
   label       Create, list, modify, or delete labels
   assign      Assign an issue to yourself (or someone else)
   milestone   Manage project milestones
   status      Determine whether or not issues are enabled for this repo
   enable      Enable issues for the current repo
   disable     Disable issues for the current repo

See 'ghi help <command>' for more information on a specific command.
```

ps. how to call it out ? ⬇️ ？

```
hub issue --help
```

**Comment by mislav** [comment]
@fuchao2012 You can use `hub help --issue` for more expanded documentation.

**Comment by fuchao2012** [comment]
Got it, thanks. 
How can i get the full-long desc of this function ?

**Comment by mislav** [comment]
> How can i get the full-long desc of this function ?

What do you mean by "full-long desc" and "this function"?

**Comment by thurt** [comment]
@mislav your command must be a typo because when i try `hub help --issue` i get `error: unknown option 'issue'`

I am using hub 2.2.9

when i try `hub issue --help` i get:
```
usage: git issue

List summary of open issues for the project that the "origin" remote points to.
```
ie. there is no description of the `hub issue create` command

**Comment by mislav** [comment]
@thurt Try the latest prerelease version from the Releases section of this repo.

**Comment by alphaCTzo7G** [comment]
I noticed the the Hub manual doesnt mention anything about the `create issues` part. https://hub.github.com/hub.1.html

Perhaps this needs to be updated

**Comment by alphaCTzo7G** [comment]
Is there a way to edit existing issues? I can check issues in the current repo? Dont see that in the man page

It seems there are 2 repos which do provide this functionality: https://github.com/node-gh/gh

and 

https://github.com/stephencelis/ghi

Is there a way to use them/merge them into this repo, instead of redoing their work?

**Comment by mislav** [comment]
@alphaCTzo7G Editing issues isn't supported, although that feature may be coming soon.

The other projects that you referenced are not mergeable in this repo because they have separate codebases. However, nothing is stopping you from using those projects for editing issues until hub gains support for it.

**Comment by alphaCTzo7G** [comment]
Ok.. I understand.. I am using `ghi` and `hqub` now.. Do you think we could have `ghi` as a dependency of `hub`? So when I user installs `hub`, they also install `ghi`/`nh` automatically, from the `stephencelis/ghi` repo? Then `ghi` is aliased or wrapped to `hub`, so they get the same functionality of `ghi` but through `hub`?

I primarily use `ghi`, and haven't used `nh`, but the commands used by `ghi` don't conflict with that of `hub`, 

   list        List your issues (or a repository's)
   show        Show an issue's details
   open        Open (or reopen) an issue
   close       Close an issue
   lock        Lock an issue's conversation, limiting it to collaborators
   unlock      Unlock an issue's conversation, opening it to all viewers
   edit        Modify an existing issue
   comment     Leave a comment on an issue
   label       Create, list, modify, or delete labels
   assign      Assign an issue to yourself (or someone else)
   milestone   Manage project milestones
   status      Determine whether or not issues are enabled for this repo
   enable      Enable issues for the current repo
   disable     Disable issues for the current repo

Both `hub` and `ghi` user Ruby. 

For users, it would be much simpler to install `hub` and get all the functionalities. Most people wont discover `ghi`/`nh` right away. 

This issue has been open since 3 years.. and the functionality is still not there in `hub`. I understand that you are the only one working on this repo, so it would get the same functionality to users, quicker..

**Comment by groscoe2** [comment]
- [ ] Update train performance calculator for mass-strap based resistance
- [ ] Fix up car-based train resistance calculation
- [ ] Integrate train performance calculator with single train dispatching output
- [ ] Develop speed profile output for Python-based powertrain energy calculators
