### ISSUE TITLE
Add command to clean all merged branches

### ISSUE THREAD

**Issue by ProLoser** [github/hub#906]
I realize this isn't specific to github, but it may be nice to get the feature in here sooner than git.

It would be nice to have some sort of `git flush` type command that 1: performs `git fetch -p` and 2: `git branch --merged | grep -v "\*" | xargs -n 1 git branch -d` to clean all local merged branches.

It would also be nice if it logged an informational message in the console that linked you to github's branches page so we can review and remove all merged or closed branches.

**Comment by hkdobrev** [comment]
I have an alias for that combined with `git remote prune origin`.

**Comment by mislav** [comment]
That's a good idea and is an action I have a shell script for myself. However, I don't think it's a great fit for the hub project. First of all, it's not related to GitHub in any way, meaning it can just as well be a standalone script.

Second, the deletion approach is simplistic and may inadvertantly branches that you didn't want deleted. For instance, suppose I do `git checkout -b fix-bug-123 origin/master` to start a bugfix topic, but before I committed anything to it, I checkout master again and do delete-merged-branches command. Now my "fix-bug-123" branch is gone because it was identical to "master", but I didn't get to do any work in it yet.

Or, suppose I merge `origin/master` into "feature" branch that I'm doing, to check if my code is still compatible with upstream. However, running `delete-merged-branches` now will delete "master" branch because technically it's merged in the current branch.

Bulk deleting branches is a tricky operation and I'd rather not that we deal with it.

**Comment by blueyed** [comment]
Just for reference: I am using this Zsh function for this: https://github.com/blueyed/oh-my-zsh/commit/f5c7d3cb2989dee80869ddabc74869a13fb9877a
