### ISSUE TITLE
how is the workflow for addressing review comments?

### ISSUE THREAD

**Issue by tfarina** [github/hub#908]
After the first pull-request, how address reviewer feedback without getting the following message?

```
# address changes
$ git commit --amend
$ git push tfarina fix-issue-1234
...
To https://github.com/tfarina/libtrading.git
 ! [rejected]        fix-issue-81 -> fix-issue-81 (non-fast-forward)
error: failed to push some refs to 'https://github.com/tfarina/libtrading.git'
To prevent you from losing history, non-fast-forward updates were rejected
Merge the remote changes (e.g. 'git pull') before pushing again.  See the
'Note about fast-forwards' section of 'git push --help' for details.
```

The documentation is not clear of how to address that after the first pull request, which is pretty frustrating!

**Comment by mislav** [comment]
Hi @tfarina 

Your question is more of a general git question instead of an issue with hub (which doesn't handle the `git push` itself). Whenever you `--amend` a commit that was already pushed to a branch and try to push the same branch again, by default git will complain about that to prevent you from "losing history". What this means in general is that rewriting commits is a potentially destructive action, and pushing the result of rewriting commits to a remote is something that is not part of conventional workflows since it can trip up other people working on the same branch.

However, in this case I presume that you're pushing to update your own PR, and you're the only person working on it at the moment. In that case it should be fine to amend commits (I do it all the time myself). You simply have to add the `-f | --force` flag:

```
git push -f tfarina fix-issue-1234
```

This tells git: “I'm aware that I rewrote history of this branch but I'm sure I know what I'm doing and want to update this branch on the remote.”

**Comment by tfarina** [comment]
Gerrit seems to handle this transparently and understands that I'm uploading a new patchset. I did that in a PR and the result that was merged was something that landed with the original commit message (which I edited) with the new changes, which is pretty confusing.

Yes, I'm the only one working on that branch. Are you saying that -f, whichI'm aware of, is the answer for my example? Is that the worflow used when contributinng in GitHub with pull-requests?

**Comment by mislav** [comment]
Yes, force-pushing is the answer to your initial problem.

As a more general answer: GitHub Pull Requests are centered around a single branch that you've opened the PR from (also referred to as the "head" of the PR), and the only way to update the code in the PR is to push to this branch again. (So, the substitute for a patchset in Gerrit is the contents of a git branch.) You may push new commits on top of old ones, which is what most people usually do, or you might rewrite old commits with `--amend` or `git rebase`, and that is when you simply need to force-push or git won't let you update the branch.

This is a repository for a command-line tool called "hub", though, and I feel your question is a general question regarding GitHub functionality. Did you have a problem using "hub" and did you expect it to handle anything better or in a more user-friendly way? If not, once I answered your questions regarding PRs I would be grateful if you closed this issue. Thanks!

**Comment by tfarina** [comment]
Yes, I think the documentation in https://hub.github.com/, could be more clear to what should be done after the initial pull request, but it is silently about it at this moment (maybe on purpose?).

OK, I think my question is more a general issue with GitHub pull-requests than with hub itself, so as requested I'm going to close this.

I will try GitHub support for this next time.

**Comment by mislav** [comment]
Thanks!
