### ISSUE TITLE
Get Upstream changes from another branch and merge into current feature branch

### ISSUE THREAD

**Issue by samjbmason** [github/hub#921]
This would be very similar to @defunkt github gem functionality on merging in changes upstream.

If this is something that can already be done apologies.

**Comment by mislav** [comment]
No, hub doesn't help you do something like that. I do it manually with `git fetch origin master && git merge origin/master`. Is this what you had in mind?

It's generally simple to do manually, so I don't think we'd be trackling this problem.

**Comment by samjbmason** [comment]
Ah thats makes sense. I think its pretty common `User A` creates `feature-a` branch from `master` but then after working on it for some time wants to get any changes that have been made to `master` and add that into `feature-a`. Im not sure when I explained it first time that I did a very good job

**Comment by mislav** [comment]
Yeah, that's pretty common. The problem is we can't tell which branch you started your work from, so you'd still need to explicitly say you want to merge `origin/master` as upstream. The one thing I can see being easier for the user is if they didn't have to manually `fetch` before merging to get the latest state of upstream. Adding a custom flag like `git merge --fetch origin/master` might help, however I'm wary of extending any more core git commands in hub, as I think it adds to confusion in the long run.

**Comment by samjbmason** [comment]
Ah yeah that is very understandable. What would be the steps you would run now if you wanted to perform this in git (If you dont mind me asking)?

**Comment by mislav** [comment]
I already said above: if the upstream branch is master, then you would reintegrate latest version of upstream in your branch like so:

1. `git fetch origin master`
2. `git merge origin/master`
