### ISSUE TITLE
"This API can only be accessed with username and password Basic Auth" on create or pull-request

### ISSUE THREAD

**Issue by matschaffer** [github/hub#965]
Can't seem to find anything like this in the issue list that covers this. I just installed hub on a new laptop and my usual pull-request command just shows:

```
❯ hub pull-request
Error creating pull request: Forbidden (HTTP 403)
This API can only be accessed with username and password Basic Auth
```

This was both before & after setting `GITHUB_*` env vars. Using password from an auth token since my account if MFA.

```
❯ hub version
git version 2.4.6
hub version 2.2.1
```

Not sure how best to debug this further.

If there's a more appropriate place for support tickets please let me know.

Thanks in advance!

**Comment by matschaffer** [comment]
Looks like `hub fork` also yields the same error.

**Comment by mislav** [comment]
What does "MFA" mean for your account?

Hub doesn't support using an OAuth token instead of your password just yet. Instead, you can drop your OAuth token manually within hub configuration so you don't get prompted for any of your credentials anymore. Create a `~/.config/hub` file:

```
---
github.com:
- protocol: https
  user: matschaffer
  oauth_token: YOUROAUTHTOKEN
```

If you're using GitHub Enterprise, instead of "github.com" above put the domain of your Enterprise instance. Let me know if this works. Sorry for the trouble. We're working on improving this flow.

**Comment by matschaffer** [comment]
Sorry, MFA == two factor authentication (https://help.github.com/articles/about-two-factor-authentication/)

Maybe hub doesn't support having that enabled?

This is against github.com rather than enterprise.

Is there somewhere in the UI can I create an oauth token manually or do I need curl the API?

**Comment by mislav** [comment]
We do support 2FA. Just use your regular password when the hub asks you for it on the command-line. Your password will never get stored anywhere.

**Comment by matschaffer** [comment]
Ah, actually I think I'd assumed I needed a authentication token which is what I was trying to use as a password. Tried just my regular u/p today, did the 2fa and everything went well.

Thanks for the assist and apologies for the noise.
