### ISSUE TITLE
abandoning pull requests

### ISSUE THREAD

**Issue by nightpool** [github/hub#979]
if hub pull-request opens a text editor, it should follow git convention and allow an empty description to signal "abandon the pull request" instead of going ahead with it.

**Comment by mislav** [comment]
Pull requests allow empty description. The git convention is to abort making a commit when the subject line is empty (commits also allow empty descriptions). We follow that convention by aborting the pull request if there is no subject line.

So, simply leave the entire pull request message blank in order to abort the pull request (you could for instance close the text editor without saving), or instruct your text editor to exit with a non-zero status (in Vim: `:cq`).

**Comment by nightpool** [comment]
This doesn't work though, my pull request just gets created with the
default text.

**Comment by mislav** [comment]
What is the default text? If there was only 1 commit in the branch, then the default text will be inherited from that commit message. This is the only case in which we do this. In this case, you have to delete the text before saving the message.
