### ISSUE TITLE
update blame command to open on github with -g|--github option

### ISSUE THREAD

**Issue by iki** [github/hub#985]
https://git-scm.com/docs/git-blame

**Comment by mislav** [comment]
Hey @iki that's not a bad idea, but we'll take a break from extending core git commands right now and instead focus on improving hub custom commands like `hub browse`. You should be able to more easily navigate to online blame view with a better `browse` command. But we won't add any new flags to `git blame` right now.

**Comment by iki** [comment]
@mislav imo extending `git blame` cmd has much better ux: the user already knows the syntax and can easily switch between console/github display command

**Comment by mislav** [comment]
I understand, it's just that I don't believe right now online blame would be any better than blame in the console. If you already have the syntax for blame on the command-line, I would say just go ahead and do it in the console since it would be much faster and you have more options to drill down into history.

**Comment by iki** [comment]
That's matter of preference, github blame is faster to overview with user icons and clickable commits. The main reason is the blame URL though, that can be passed to discussion on issues/PRs/slack/...
