### ISSUE TITLE
git create needs a way to make '-p' the default

### ISSUE THREAD

**Issue by timlesallen** [github/hub#996]
We use hub for commercial projects and have experienced some security issues as a result of forgetting to specify the '-p' option when doing a `git create`.  Is there some way I don't know of (or a workaround) to make this the default?  We do create public repositories now and then but would much rather that have to be explicit and private be the implicit default, rather than the other way around.  Would like to see this possible in some way.

**Comment by marcusmueller** [comment]
@timlesallen that's more of a feature request and discussion than a bug report. Now, this is free and open source, so I recommend reading the code: https://github.com/github/hub/blob/master/commands/create.go#L34

It shouldn't be hard for a commercially interested party like you to add support for configurability of the default value of `flag_create_private`. Basically, this is how Free Software works: you use it for your own good, and when you need it to do more than it currently can, you improve it and, in the best case, contribute back.

**Comment by mislav** [comment]
@timlesallen I'm interested in having both global config and local (per-project) config for hub subcommands that would allow you to specify default flags and values. That would solve your situation, since you would be able to specify that all `hub create`s should be done with `-p`. That would entail that there needs to be a new `--public` option to counter the default, however.

**Comment by mislav** [comment]
Closing in favor of the default config idea: #964
