### ISSUE TITLE
hub fork doesn't create the correct remote url

### ISSUE THREAD

**Issue by pgilad** [github/hub#997]
Created `git` remote url instead of `https` even though I have in my hub.config:

`protocol: https`

**Comment by mislav** [comment]
Hi there! If you're looking at `~/.config/hub` and see `protocol: https`, that's not for git remotes. That's for GitHub API HTTP calls. (Some GitHub Enterprise hosts need to be configured with HTTP protocol instead of HTTPS.)

If you want to configure your default protocol for git operations, do:

```
git config --global hub.protocol https
```

[This is specified in the man page](https://hub.github.com/hub.1.html) under "Configuration".
